#!/usr/bin/env bash

set -e

# Ensure the ~/.local/bin directory exists so we can download things into it.
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"

# A helper function to download an architecture-dependent AppImage and install
# it in ~/.local/bin.
#
# Usage:
#   download_appimage $BINARY_NAME $VERSION $DOWNLOAD_URL_BASE
#
# Args:
#   BINARY_NAME:       The name of the AppImage-bundled binary we want to
#                      download, e.g.: "appimagetool".
#   VERSION:           The upstream release tag; embedded in the cached
#                      filename so bumping it forces a re-download.
#   DOWNLOAD_URL_BASE: The URL to the directory containing the architecture-
#                      specific AppImages.
download_appimage() {
  BINARY_NAME="$1"
  VERSION="$2"
  DOWNLOAD_URL_BASE="$3"

  APPIMAGE_PATH="$LOCAL_BIN/$BINARY_NAME-$VERSION-$(uname -m).AppImage"

  if [ ! -x "$APPIMAGE_PATH" ]; then
    APPIMAGE_RELEASE_URL="$DOWNLOAD_URL_BASE/$BINARY_NAME-$(uname -m).AppImage"
    echo "⬇️  Downloading $APPIMAGE_RELEASE_URL..."
    curl -fL "$APPIMAGE_RELEASE_URL" --output "$APPIMAGE_PATH"
    chmod +x "$APPIMAGE_PATH"
  fi

  # Create a symlink so we can invoke it like a normal binary.
  ln -sf "$APPIMAGE_PATH" "$LOCAL_BIN/$BINARY_NAME"
}

# Install linuxdeploy, a helper for constructing an AppDir (and then invoking
# appimagetool).
LINUXDEPLOY_VERSION="1-alpha-20251107-1"
download_appimage "linuxdeploy" "$LINUXDEPLOY_VERSION" \
  "https://github.com/linuxdeploy/linuxdeploy/releases/download/$LINUXDEPLOY_VERSION/"

if [ ! -x "$(which linuxdeploy)" ]; then
  echo -e "⚠️  ${red}Please make sure that \"$LOCAL_BIN\" is on your PATH, otherwise some scripts may not work.${reset}"
fi
