# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/persistence/src/schema.rs"
# Don't allow all tables in the same query; only allow ones that have foreign key relationships.
# This vastly reduces the number of generated trait implementations and compilation time.
allow_tables_to_appear_in_same_query_config = "fk_related_tables"
# Custom patch file (generated via `git diff -U6 > crates/persistence/schema.patch`) so that
# we can update the schema generated via diesel to use a type other than the default.
patch_file = "crates/persistence/schema.patch"
