# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/persistence/src/schema.rs"
# Don't allow all tables in the same query; only allow ones that have foreign key relationships.
# This vastly reduces the number of generated trait implementations and compilation time.
allow_tables_to_appear_in_same_query_config = "fk_related_tables"
