//! Contains the v2 implementation of internal suggestion generation logic that depends on the new
//! JS-compatible command signatures struct (crate::signatures::CommandSignature).
use std::collections::HashMap;

use crate::completer::engine::{self, CompletionLocation};
use crate::completer::LocationType;
use crate::{parsers::ClassifiedCommand, signatures::Command};

use super::{CompleterOptions, CompletionContext, MatchedSuggestion, SuggestionTypeName};

/// Returns a map of `SuggestionType` to vectors of `MatchedSuggestion`s for `input`.
///
/// For every given `SuggestionType` in `suggestion_types_to_complete_on`, corresponding suggestions
/// of that type (e.g. flag, argument, command) are generated by suggestion-type-specific
/// functions, e.g. `engine::argument_suggestions()`.
///
/// This is a fork of `super::legacy::completion_results_from_locations` that is compatible with V2
/// the Command Signatures struct.
#[allow(clippy::too_many_arguments)]
pub(super) async fn completion_results_from_locations<'a>(
    input: &str,
    classified_command: Option<ClassifiedCommand>,
    tokens_without_last_editing: &[&str],
    found_signature: Option<&'a Command>,
    locations: Vec<CompletionLocation>,
    session_env_vars: Option<&HashMap<String, String>>,
    options: &CompleterOptions,
    ctx: &'a dyn CompletionContext,
) -> HashMap<SuggestionTypeName, Vec<MatchedSuggestion>> {
    let mut completion_results_by_type =
        HashMap::<SuggestionTypeName, Vec<MatchedSuggestion>>::new();

    // For each location type, build up a single completion result for the
    // corresponding suggestion type.
    for location in locations {
        match location.item {
            LocationType::Command { parsed_token, .. } => {
                let results =
                    engine::command_suggestions(ctx, options.match_strategy, &parsed_token).await;
                completion_results_by_type
                    .entry(SuggestionTypeName::Command)
                    .or_default()
                    .extend(results);
            }
            LocationType::Variable { parsed_token } => {
                if let Some(env_vars) = ctx.environment_variable_names() {
                    let results = engine::variable_suggestions(
                        options.match_strategy,
                        env_vars,
                        &parsed_token,
                    );
                    completion_results_by_type
                        .entry(SuggestionTypeName::Variable)
                        .or_default()
                        .extend(results);
                }
            }
            LocationType::Flag { .. } => {
                let results =
                    engine::flag_suggestions(options.match_strategy, &location, found_signature);
                completion_results_by_type
                    .entry(SuggestionTypeName::Option)
                    .or_default()
                    .extend(results);
            }
            LocationType::Argument {
                ref parsed_token, ..
            } => {
                if let Some(classified_command) = classified_command.as_ref() {
                    let results = engine::argument_suggestions(
                        input,
                        tokens_without_last_editing,
                        classified_command.clone(),
                        found_signature,
                        &location,
                        session_env_vars,
                        parsed_token,
                        options,
                        ctx,
                    )
                    .await;
                    completion_results_by_type
                        .entry(SuggestionTypeName::Argument)
                        .or_default()
                        .extend(results);
                }
            }
        }
    }

    completion_results_by_type
}
