use chrono::{Duration, Utc};
use settings::manager::SettingsManager;
use warpui::{App, SingletonEntity};

use crate::ai::facts::{AIFact, AIFactObject, AIFactObjectModel, AIMemory};
use crate::auth::AuthStateProvider;
use crate::cloud_object::model::persistence::CloudModel;
use crate::cloud_object::model::view::CloudViewModel;
use crate::cloud_object::update_manager::UpdateManager;
use crate::cloud_object::{CloudObjectMetadata, CloudObjectPermissions, Revision};
use crate::notebooks::manager::NotebookManager;
use crate::search::ai_context_menu::rules::data_source::RulesDataSource;
use crate::search::data_source::Query;
use crate::search::mixer::SyncDataSource;
use crate::server::ids::SyncId;
use crate::settings::AISettings;
use crate::system::SystemStats;
use crate::workspaces::user_profiles::UserProfiles;
use crate::workspaces::user_workspaces::UserWorkspaces;
use crate::NetworkStatus;

fn mock_ai_fact(id: i64, name: &str, content: &str, revision: Revision) -> AIFactObject {
    let sync_id = SyncId::ServerId(id.into());
    let mut metadata = CloudObjectMetadata::mock();
    metadata.revision = Some(revision);

    AIFactObject::new(
        sync_id,
        AIFactObjectModel::new(AIFact::Memory(AIMemory {
            name: Some(name.to_string()),
            content: content.to_string(),
            is_autogenerated: false,
            suggested_logging_id: None,
        })),
        metadata,
        CloudObjectPermissions::mock_personal(),
    )
}

fn initialize_app(app: &mut App) {
    app.add_singleton_model(|_| NetworkStatus::new());
    app.add_singleton_model(|_| SystemStats::new());
    app.add_singleton_model(|ctx| UserWorkspaces::mock(vec![], ctx));
    app.add_singleton_model(CloudModel::mock);
    app.add_singleton_model(|ctx| UpdateManager::new(None, ctx));
    app.add_singleton_model(|_| UserProfiles::new(Vec::new()));
    app.add_singleton_model(CloudViewModel::new);
    app.add_singleton_model(NotebookManager::mock);
    app.add_singleton_model(|_| SettingsManager::default());
    app.add_singleton_model(|_| AuthStateProvider::new_for_test());
    app.update(crate::settings::init_and_register_user_preferences);
    app.update(AISettings::register_and_subscribe_to_events);
}

#[test]
fn zero_state_scores_reflect_recency() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);

        let now = Utc::now();
        CloudModel::handle(&app).update(&mut app, |model, _| {
            for fact in [
                mock_ai_fact(
                    1,
                    "oldest rule",
                    "oldest content",
                    (now - Duration::minutes(3)).into(),
                ),
                mock_ai_fact(
                    2,
                    "middle rule",
                    "middle content",
                    (now - Duration::minutes(2)).into(),
                ),
                mock_ai_fact(
                    3,
                    "newest rule",
                    "newest content",
                    (now - Duration::minutes(1)).into(),
                ),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let data_source = RulesDataSource::new();
        let results = app.read(|app| data_source.run_query(&Query::from(""), app).unwrap());

        assert_eq!(results.len(), 3);
        let scores: Vec<_> = results.iter().map(|r| r.score()).collect();
        assert!(
            scores[0] > scores[1] && scores[1] > scores[2],
            "Expected scores in strictly descending order (newest first), got {scores:?}"
        );
    })
}

#[test]
fn filtered_state_adds_recency_bonus() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);

        let now = Utc::now();
        // All rules contain "rule" so fuzzy scores should be similar
        CloudModel::handle(&app).update(&mut app, |model, _| {
            for fact in [
                mock_ai_fact(
                    1,
                    "my first rule",
                    "first rule content",
                    (now - Duration::minutes(3)).into(),
                ),
                mock_ai_fact(
                    2,
                    "my second rule",
                    "second rule content",
                    (now - Duration::minutes(2)).into(),
                ),
                mock_ai_fact(
                    3,
                    "my third rule",
                    "third rule content",
                    (now - Duration::minutes(1)).into(),
                ),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let data_source = RulesDataSource::new();
        let results = app.read(|app| data_source.run_query(&Query::from("rule"), app).unwrap());

        assert_eq!(results.len(), 3);
        let scores: Vec<_> = results.iter().map(|r| r.score()).collect();
        assert!(
            scores[0] > scores[1] && scores[1] > scores[2],
            "Expected scores in strictly descending order (newest first), got {scores:?}"
        );
    })
}
