use std::sync::Arc;

use chrono::{Duration, Utc};
use settings::manager::SettingsManager;
use warpui::{App, SingletonEntity};

use crate::ai::facts::{AIFact, AIMemory, CloudAIFactModel};
use crate::auth::AuthStateProvider;
use crate::cloud_object::model::generic_string_model::GenericStringModel;
use crate::cloud_object::model::persistence::CloudModel;
use crate::cloud_object::model::view::CloudViewModel;
use crate::cloud_object::{
    GenericServerObject, Owner, Revision, ServerMetadata, ServerPermissions,
};
use crate::notebooks::manager::NotebookManager;
use crate::search::ai_context_menu::rules::data_source::RulesDataSource;
use crate::search::data_source::Query;
use crate::search::mixer::SyncDataSource;
use crate::server::cloud_objects::update_manager::UpdateManager;
use crate::server::ids::{ServerId, SyncId};
use crate::server::server_api::ServerApiProvider;
use crate::server::sync_queue::SyncQueue;
use crate::settings::AISettings;
use crate::system::SystemStats;
use crate::workspaces::team_tester::TeamTesterStatus;
use crate::workspaces::user_profiles::UserProfiles;
use crate::workspaces::user_workspaces::UserWorkspaces;
use crate::NetworkStatus;

use crate::server::server_api::object::MockObjectClient;
use crate::server::server_api::team::MockTeamClient;
use crate::server::server_api::workspace::MockWorkspaceClient;

type ServerAIFact = GenericServerObject<
    crate::cloud_object::model::generic_string_model::GenericStringObjectId,
    CloudAIFactModel,
>;

fn mock_server_ai_fact(id: i64, name: &str, content: &str, revision: Revision) -> ServerAIFact {
    GenericServerObject {
        id: SyncId::ServerId(id.into()),
        metadata: ServerMetadata {
            uid: ServerId::default(),
            revision,
            metadata_last_updated_ts: Utc::now().into(),
            trashed_ts: None,
            folder_id: None,
            is_welcome_object: false,
            creator_uid: None,
            last_editor_uid: None,
            current_editor_uid: None,
        },
        permissions: ServerPermissions {
            space: Owner::mock_current_user(),
            guests: Vec::new(),
            anyone_link_sharing: None,
            permissions_last_updated_ts: Utc::now().into(),
        },
        model: GenericStringModel {
            string_model: AIFact::Memory(AIMemory {
                name: Some(name.to_string()),
                content: content.to_string(),
                is_autogenerated: false,
                suggested_logging_id: None,
            }),
        },
    }
}

fn initialize_app(app: &mut App) {
    app.add_singleton_model(|_| NetworkStatus::new());
    app.add_singleton_model(|_| SystemStats::new());
    let mock_team_client = Arc::new(MockTeamClient::new());
    let mock_workspace_client = Arc::new(MockWorkspaceClient::new());
    app.add_singleton_model(|ctx| {
        UserWorkspaces::mock(
            mock_team_client.clone(),
            mock_workspace_client.clone(),
            vec![],
            ctx,
        )
    });
    app.add_singleton_model(TeamTesterStatus::new);
    app.add_singleton_model(SyncQueue::mock);
    app.add_singleton_model(CloudModel::mock);
    app.add_singleton_model(|ctx| UpdateManager::new(None, Arc::new(MockObjectClient::new()), ctx));
    app.add_singleton_model(|_| UserProfiles::new(Vec::new()));
    app.add_singleton_model(CloudViewModel::new);
    app.add_singleton_model(NotebookManager::mock);
    app.add_singleton_model(|_| ServerApiProvider::new_for_test());
    app.add_singleton_model(|_| SettingsManager::default());
    app.add_singleton_model(|_| AuthStateProvider::new_for_test());
    app.update(crate::settings::init_and_register_user_preferences);
    app.update(AISettings::register_and_subscribe_to_events);
}

#[test]
fn zero_state_scores_reflect_recency() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);

        let now = Utc::now();
        CloudModel::handle(&app).update(&mut app, |model, ctx| {
            model.upsert_from_server_object(
                mock_server_ai_fact(
                    1,
                    "oldest rule",
                    "oldest content",
                    (now - Duration::minutes(3)).into(),
                ),
                ctx,
            );
            model.upsert_from_server_object(
                mock_server_ai_fact(
                    2,
                    "middle rule",
                    "middle content",
                    (now - Duration::minutes(2)).into(),
                ),
                ctx,
            );
            model.upsert_from_server_object(
                mock_server_ai_fact(
                    3,
                    "newest rule",
                    "newest content",
                    (now - Duration::minutes(1)).into(),
                ),
                ctx,
            );
        });

        let data_source = RulesDataSource::new();
        let results = app.read(|app| data_source.run_query(&Query::from(""), app).unwrap());

        assert_eq!(results.len(), 3);
        let scores: Vec<_> = results.iter().map(|r| r.score()).collect();
        assert!(
            scores[0] > scores[1] && scores[1] > scores[2],
            "Expected scores in strictly descending order (newest first), got {scores:?}"
        );
    })
}

#[test]
fn filtered_state_adds_recency_bonus() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);

        let now = Utc::now();
        // All rules contain "rule" so fuzzy scores should be similar
        CloudModel::handle(&app).update(&mut app, |model, ctx| {
            model.upsert_from_server_object(
                mock_server_ai_fact(
                    1,
                    "my first rule",
                    "first rule content",
                    (now - Duration::minutes(3)).into(),
                ),
                ctx,
            );
            model.upsert_from_server_object(
                mock_server_ai_fact(
                    2,
                    "my second rule",
                    "second rule content",
                    (now - Duration::minutes(2)).into(),
                ),
                ctx,
            );
            model.upsert_from_server_object(
                mock_server_ai_fact(
                    3,
                    "my third rule",
                    "third rule content",
                    (now - Duration::minutes(1)).into(),
                ),
                ctx,
            );
        });

        let data_source = RulesDataSource::new();
        let results = app.read(|app| data_source.run_query(&Query::from("rule"), app).unwrap());

        assert_eq!(results.len(), 3);
        let scores: Vec<_> = results.iter().map(|r| r.score()).collect();
        assert!(
            scores[0] > scores[1] && scores[1] > scores[2],
            "Expected scores in strictly descending order (newest first), got {scores:?}"
        );
    })
}
