pub const ICON_SIZE: f32 = 16.0;
pub const MARGIN_RIGHT: f32 = 8.0;
pub const ESTIMATED_RESULT_HEIGHT: f32 = 24.0;
pub const MENU_ITEM_HORIZONTAL_PADDING: f32 = 16.0;
pub const MENU_ITEM_VERTICAL_PADDING: f32 = 4.0;
pub const MENU_ITEM_HIGHLIGHT_CORNER_RADIUS: f32 = 8.0;
