# Important note: This must be run after we build the release binary; this only
# packages up an already-built binary.

name: Bundle Arch Linux package
description: Bundles an Arch Linux package for the given release channel.
inputs:
  channel:
    description: The channel for which we want to build an Arch package.
    requred: true
  release-tag:
    description: The git release tag.
    required: true
  arch:
    description: The architecture we are building for
    required: true
  artifact:
    description: The artifact type to build (app or cli)
    required: false
    default: app

runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: docker build -t arch-bundle-builder ${{ github.action_path }}

    - name: Run in container
      shell: bash
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/github/workspace" \
          -v "${{ github.workspace }}/target:/github/workspace/target" \
          -w /github/workspace \
          -v "${CARGO_HOME:-$HOME/.cargo}/git:/home/build/.cargo/git" \
          -v "${CARGO_HOME:-$HOME/.cargo}/registry:/home/build/.cargo/registry" \
          -e GIT_RELEASE_TAG="$GIT_RELEASE_TAG" \
          -e GITHUB_ACTIONS="$GITHUB_ACTIONS" \
          -e GITHUB_OUTPUT="/dev/null" \
          arch-bundle-builder \
          ${{ inputs.channel }} ${{ inputs.release-tag }} ${{ inputs.arch }} ${{ inputs.artifact }}
