//! Asset-source glue for typeset LaTeX math, mirroring `mermaid_diagram.rs`.
//!
//! Math SVG is generated by the `math_render` crate and drawn through the
//! standard image pipeline (`AssetSource::Async` → SVG bytes → `ImageType`).
//! The glyph color is baked into the SVG, so it participates in the asset id:
//! a theme change produces a new id and a fresh render instead of a stale
//! wrongly-colored cache hit.

use std::hash::{DefaultHasher, Hash, Hasher};
use std::sync::Arc;

use bytes::Bytes;
use warpui_core::assets::asset_cache::{AssetSource, AsyncAssetId, AsyncAssetType};

struct MathBlockAsset;

impl AsyncAssetType for MathBlockAsset {}

/// Build an [`AssetSource`] that typesets `latex` (math-mode source, no
/// delimiters) as a self-contained SVG in the given CSS color (e.g. `#e0e0e0`)
/// at `font_size` logical pixels per em.
pub fn math_asset_source(latex: &str, display: bool, color: &str, font_size: f64) -> AssetSource {
    let mut hasher = DefaultHasher::new();
    latex.hash(&mut hasher);
    display.hash(&mut hasher);
    color.hash(&mut hasher);
    font_size.to_bits().hash(&mut hasher);
    let id = format!("math:{:x}", hasher.finish());

    let latex = latex.to_string();
    let color = color.to_string();
    AssetSource::Async {
        id: AsyncAssetId::new::<MathBlockAsset>(id),
        fetch: Arc::new(move || {
            let latex = latex.clone();
            let color = color.clone();
            Box::pin(async move {
                math_render::render_math_to_svg(&latex, display, &color, font_size)
                    .map(|svg| Bytes::from(svg.into_bytes()))
                    .map_err(Into::into)
            })
        }),
    }
}

/// Reconstruct the markdown source for a display-math block.
pub fn markdown_source_for_math(latex: &str) -> String {
    format!("$${latex}$$")
}
