name: Bug Report
description: "Found a bug? We'd appreciate if you'd first search through our open issues and docs, to make sure the issue isn't already known."
labels: ["Bug"]
body:
  - type: input
    id: "discord"
    attributes:
      label: "Discord username (optional)"
      description: "If you're in our Discord server please include your formatted like so: elvis#4747. This is so we can give you the Bug Catcher Discord role."
      placeholder: username#4747
    validations:
      required: false
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: Tell us what you see.
    validations:
      required: true
  - type: textarea
    id: "to-reproduce"
    attributes:
      label: "To reproduce"
      description: "Bug reports with clear reproduction will get prioritized higher and addressed more quickly."
      placeholder: "Steps to reproduce: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error '...'"
    validations:
      required: true
  - type: textarea
    id: "expected-behavior"
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: Tell us what you expect to see.
    validations:
      required: false
  - type: textarea
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem. While optional, screenshots help expedite the time in which your bug is addressed."
    validations:
      required: false
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating system"
      multiple: false
      options:
        - MacOS
        - Linux
        # - Windows
    validations:
      required: true
  - type: input
    id: "os-version"
    attributes:
      label: "Operating system and version"
      description: "For example: Debian 11.2"
    validations:
      required: true
  - type: input
    id: "local-shell-version"
    attributes:
      label: "Shell Version"
      description: "For example, `bash 4.0` e.g. Run `bash --version` or `zsh --version`"
    validations:
      required: false
  - type: input
    id: "warp-version"
    attributes:
      label: "Current Warp version"
      description: "Open the Settings Dialog (CMD-,) using the Command Palette or by clicking the three dots > Settings > Account. Once you're on the Account page click the copy icon that's to the right of the version number. `v0.2047.04.07.47.47.stable_47`"
    validations:
      required: false
  - type: dropdown
    id: "regression"
    attributes:
      label: "Regression"
      description: "Is this a regression (used to work in a previous Warp version)?"
      multiple: false
      options:
        - "No, this bug or issue has always existed in my team using Warp"
        - "Yes, this bug started recently or with an X Warp version"
    validations:
      required: true
  - type: input
    id: "warp-version-regression"
    attributes:
      label: "Most recent working Warp version"
      description: "Open the Settings Dialog (CMD-,) using the Command Palette or by clicking the three dots > Settings > Account. Once you're on the Account page click the copy icon that's to the right of the version number. `v0.2047.04.07.47.47.stable_47`"
    validations:
      required: false
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
  - type: dropdown
    id: "blocker"
    attributes:
      label: "Does this block you from using Warp daily?"
      description: "All feedback will be reviewed, even if you select 'No'."
      multiple: false
      options:
        - "No"
        - "Yes, this issue prevents me from using Warp daily."
    validations:
      required: true
  - type: dropdown
    id: "terminals"
    attributes:
      label: "Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)"
      description: "Verifying this issue doesn't happen in other terminals helps us to prioritize the fix"
      multiple: false
      options:
        - "No, this same issue happens in Warp and other terminals."
        - "Yes, this I confirmed this only happens in Warp, not other terminals."
        - "N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)"
    validations:
      required: true
  - type: dropdown
    id: "linear-label-bug"
    attributes:
      label: "Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e"
      multiple: false
      options:
        - Ignore
    validations:
      required: false

