name: Feature Request
description: "Have a great new idea? Please search through our existing feature requests, and upvote it if it's already exists."
labels: ["Feature requests"]
body:
  - type: checkboxes
    attributes:
      label: "Pre-submit Checks"
      options:
        - label: "I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates"
          required: true
        - label: "I have [searched Warp docs](https://docs.warp.dev) and my feature is not there"
          required: true
  - type: textarea
    id: "describe-solution"
    attributes:
      label: "Describe the solution you'd like?"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: "related-to-problem"
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: false
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here. If you want to upload a picture you can drag one in from Finder."
    validations:
      required: false
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating system (Optional, if relevant)"
      multiple: false
      options:
        - MacOS
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: "importance"
    attributes:
      label: "How important is this feature to you?"
      multiple: false
      options:
        - "1 (Not too important)"
        - "2"
        - "3"
        - "4"
        - "5 (Can't work without it!)"
    validations:
      required: true
  - type: dropdown
    id: "linear-label-feature"
    attributes:
      label: "Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1"
      multiple: false
      options:
        - Ignore
    validations:
      required: false
