name: Feature Request
description: "Have a great new idea? We'd love to know, please look through our existing issues, and upvote it if its already been filed."
body:
  - type: input  
    id: "discord"
    attributes:
      label: "Discord username (optional)"
      description: "If you're in our Discord server please include your formatted like so: elvis#4747. This is so we can give you the Bug Catcher Discord role."
      placeholder: username#4747
    validations:
      required: false
  - type: textarea
    id: "describe-solution"
    attributes:
      label: "Describe the solution you'd like?"
      description: "A clear and concise description of what you want to happen."
      render: text
    validations:
      required: true
  - type: textarea
    id: "related-to-problem"
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when [...]"
      render: text
    validations:
      required: false
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here. If you want to upload a picture you can drag one in from Finder."
    validations:
      required: false
  - type: dropdown
    id: "triage"
    attributes:
      label: "Warp Internal (ignore) - linear-label:efcea52d-0ab4-4a92-a41b-93c3e244f0a0"
      multiple: false
      options:
        - Ignore
        # - Windows
        # - Linux
    validations:
      required: false
