name: SSH Warpify Issues? Use this template
description: "Issue template specialized for the circumstances where SSH Warpification with tmux fails"
labels: ["Bugs","SSH-tmux"]
body:
  - type: markdown
    attributes:
      value: "<img width="431" alt="image" src="https://github.com/user-attachments/assets/0fd16fe3-e2c1-4ef0-9267-46320c2db903" />
      
      To get terminal output, click on the top right icon of your terminal block, select `Copy`"
  - type: textarea
    id: "shell-output"
    attributes:
      label: "Include shell output"
      description: "Click on the top right icon of your terminal block, select `Copy`, and paste the contents here. Please redact any personal details."
      render: shell
    validations:
      required: true
  - type: dropdown
    id: "linear-label-ssh-tmux"
    attributes:
      label: "Warp Internal (ignore) - linear-label:7a739baa-09c3-499e-a0c9-a1a16c090597"
      multiple: false
      options:
        - Ignore
    validations:
      required: false
  - type: dropdown
    id: "linear-label-bug"
    attributes:
      label: "Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e"
      multiple: false
      options:
        - Ignore
    validations:
      required: false
