name: SSH Issues? Use this template
description: "Issue template specialized for the circumstances where the shell doesn't bootstrap over SSH"
body:
  - type: input
    id: "discord"
    attributes:
      label: "Discord username (optional)"
      description: "If you're in our Discord server please include your formatted like so: elvis#4747. This is so we can give you the Bug Catcher Discord role."
      placeholder: "username#4747"
    validations:
      required: false
  - type: input
    id: "local-shell"
    attributes:
      label: "Local Shell and Version"
      description: "Output of `echo $BASH_VERSION` or `echo $ZSH_VERSION`"
    validations:
      required: true
  - type: input
    id: "remote-shell"
    attributes:
      label: "Remote Shell and Version"
      description: "Output of `echo $BASH_VERSION` or `echo $ZSH_VERSION`"
    validations:
      required: true
  - type: input
    id: "os"
    attributes:
      label: "Operating System and Version"
      description: "e.g. Debian 11.2"
    validations:
      required: true
  - type: input
    id: "warp-version"
    attributes:
      label: "Warp Version"
      description: "Click the 3-dots menu docked to the right of the tabs in Warp and click the copy button, e.g. `v0.2022.05.30.09.10.stable_01`"
    validations:
      required: true
  - type: checkboxes
    id: "rcfiles"
    attributes:
      label: "I have tried commenting out my system & user rcfiles and warp still will not bootstrap"
      description: "If the issue is with your system and user rcfiles, please isolate the issue more (e.g. to a particular plugin, or a line of shell code) and open a general issue."
      options:
      - label: "Yes"
        required: true
  - type: textarea
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: "Please either include a screenshot or describe what you see."
    validations:
      required: false
  - type: textarea
    id: "xtrace-output"
    attributes:
      label: "Include shell xtrace output"
      description: "1. Ensure you're on the 3.31 version of Warp or later.
      2. Run WARP_DEBUG_MODE=1 ssh YOUR-HOSTNAME-HERE
      3. Save the full output starting from the ssh command block. If you’re not comfortable posting the outputs to a public issue, you can email feedback@warp.dev.
      "
    validations:
      required: true
  - type: dropdown
    id: "triage"
    attributes:
      label: "Warp Internal (ignore) - linear-label:018de222-5d69-45e6-ba7c-c94b9ae09495"
      multiple: false
      options:
        - Ignore
        # - Windows
        # - Linux
    validations:
      required: false
