name: Feature Request
description: "Suggest an idea for this project."
labels: [bug]
body:
  - type: textarea
    id: "related-to-problem"
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when [...]"
      render: shell
    validations:
      required: true
  - type: textarea
    id: "describe-solution"
    attributes:
      label: "Describe the solution you'd like?"
      description: "A clear and concise description of what you want to happen."
      render: shell
    validations:
      required: true
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: true