name: Get Channel Config
description: Provides a variety of config data for the given channel type.
inputs:
  config_file:
    description: The path to the configuration file.
    required: true
  channel:
    description: The channel to retrieve configuration data for.
    required: true
outputs:
  channel:
    description: The channel that we're building a release for.  (This is the same as the input value.)
    value: ${{ steps.get-config.outputs.channel }}
  type:
    description: The release type, either "nightly" or "weekly".
    value: ${{ steps.get-config.outputs.type }}
  is_prerelease:
    description: Whether this channel is a prerelease channel.
    value: ${{ steps.get-config.outputs.is_prerelease }}
  is_autopush:
    description: Whether new builds for this channel automatically trigger channel versions updates.
    value: ${{ steps.get-config.outputs.is_autopush }}
  release_base_name:
    description: The base name for the GitHub release, to which the release number is appended.
    value: ${{ steps.get-config.outputs.release_base_name }}
  release_body_text:
    description: The body text for the GitHub release.
    value: ${{ steps.get-config.outputs.release_body_text }}
  sentry_project:
    description: The Sentry project under which a new release should be created.
    value: ${{ steps.get-config.outputs.sentry_project }}
  sentry_environment:
    description: The environment to set for this channel's Sentry release.
    value: ${{ steps.get-config.outputs.sentry_environment }}
  changelog_slack_channel:
    description: The Slack channel where the release's changelog should be posted.
    value: ${{ steps.get-config.outputs.changelog_slack_channel }}
  gcs_cache_control_value:
    description: The Cache-Control value to set for release artifacts in Cloud Storage.
    value: ${{ steps.get-config.outputs.gcs_cache_control_value }}
  web_gcs_bucket_prefix:
    description: The GCS bucket prefix for web artifacts. (Determines if they go in a staging or prod bucket.)
    value: ${{ steps.get-config.outputs.web_gcs_bucket_prefix }}

runs:
  using: composite
  steps:
    - id: get-config
      env:
        CONFIG_FILE: ${{ inputs.config_file }}
        CHANNEL: ${{ inputs.channel }}
      run: |
        echo ::echo::on
        jq -e '.channels[] | select(.channel == $ENV.CHANNEL)' $CONFIG_FILE > /dev/null
        # Fail if the given channel is not found in the JSON release configuration.
        [ $? -eq 0 ] || (echo ::error::"Channel $CHANNEL not found in release configuration" && exit 1)
        jq -rc '.channels[] | select(.channel == $ENV.CHANNEL) | to_entries | map("\(.key)=\(.value)")[]' $CONFIG_FILE >> $GITHUB_OUTPUT
        echo ::echo::off
      shell: bash
