use super::*;
use std::collections::HashMap;
use std::path::Path;

use crate::launch_configs::launch_config::PaneTemplateType;
use crate::tab_configs::render_tab_config;
use crate::tab_configs::tab_config::{generated_worktree_repo_dir, TabConfigPaneType};

#[cfg(feature = "local_fs")]
#[test]
fn test_default_tab_configs_dir_uses_underscores() {
    assert!(default_tab_configs_dir().ends_with("default_tab_configs"));
}

#[cfg(feature = "local_fs")]
#[test]
fn test_is_tab_config_toml_matches_user_tab_configs() {
    let path = tab_configs_dir().join("my_tab_config.toml");
    assert!(is_tab_config_toml(&path));
}

#[cfg(feature = "local_fs")]
#[test]
fn test_is_tab_config_toml_matches_default_tab_configs() {
    let path = default_tab_configs_dir().join("worktree.toml");
    assert!(is_tab_config_toml(&path));
}

#[cfg(feature = "local_fs")]
#[test]
fn test_is_tab_config_toml_rejects_non_toml_paths() {
    let path = tab_configs_dir().join("my_tab_config.yaml");
    assert!(!is_tab_config_toml(&path));
}

#[cfg(feature = "local_fs")]
#[test]
fn test_is_tab_config_toml_rejects_tomls_outside_tab_config_dirs() {
    let path = launch_configs_dir().join("workspace.toml");
    assert!(!is_tab_config_toml(&path));
}

#[cfg(feature = "local_fs")]
#[test]
fn test_materialize_default_worktree_config_bakes_repo_and_pane_type_only() {
    let template = include_str!("../../resources/tab_configs/default_worktree.toml");
    let repo_path = "/tmp/example-repo";
    let (toml_content, tab_config) =
        materialize_default_worktree_config(template, "Worktree: example-repo", repo_path, "agent")
            .expect("expected template materialization to succeed");

    assert!(toml_content.contains("name = \"Worktree: example-repo\""));
    assert!(toml_content.contains(repo_path));
    assert!(toml_content.contains("type = \"agent\""));
    assert!(toml_content.contains("{{autogenerated_branch_name}}"));
    assert!(toml_content.contains(
        &generated_worktree_repo_dir(Path::new(repo_path))
            .display()
            .to_string()
    ));
    assert!(!toml_content.contains("{{repo}}"));
    assert!(!toml_content.contains("{{pane_type}}"));
    assert!(!toml_content.contains("{{worktree_path_prefix}}"));
    assert!(!toml_content.contains("[params.repo]"));
    assert!(!toml_content.contains("[params.pane_type]"));

    assert!(tab_config.params.is_empty());
    assert_eq!(tab_config.name, "Worktree: example-repo");
    assert_eq!(tab_config.panes.len(), 1);
    assert_eq!(tab_config.panes[0].directory.as_deref(), Some(repo_path));
    assert_eq!(
        tab_config.panes[0].pane_type,
        Some(TabConfigPaneType::Agent)
    );
}

#[cfg(feature = "local_fs")]
#[test]
fn test_materialized_default_worktree_config_renders_full_worktree_path() {
    let template = include_str!("../../resources/tab_configs/default_worktree.toml");
    let repo_path = "/tmp/example-repo";
    let (_, tab_config) =
        materialize_default_worktree_config(template, "Worktree: example-repo", repo_path, "agent")
            .expect("expected template materialization to succeed");

    let (_, pane_template) = render_tab_config(&tab_config, &HashMap::new(), Some("my-feature"));

    if let PaneTemplateType::PaneTemplate { commands, .. } = pane_template {
        let expected_worktree_path = generated_worktree_repo_dir(Path::new(repo_path))
            .join("my-feature")
            .display()
            .to_string();
        assert_eq!(commands.len(), 2);
        assert_eq!(
            commands[0].exec,
            format!("git worktree add -b my-feature {expected_worktree_path}")
        );
        assert_eq!(commands[1].exec, format!("cd {expected_worktree_path}"));
    } else {
        panic!("expected terminal pane template");
    }
}

#[cfg(feature = "local_fs")]
#[test]
fn test_sanitize_toml_base_name_replaces_spaces_and_dots() {
    assert_eq!(sanitize_toml_base_name("My Project.v2"), "my_project_v2");
}

#[cfg(feature = "local_fs")]
#[test]
fn test_sanitize_toml_base_name_falls_back_for_empty_result() {
    assert_eq!(sanitize_toml_base_name("..."), "worktree");
}
