-- PDX-71: append-only skill usage ledger.
--
-- Schema is intentionally D1-compatible (phase C will mirror this table to
-- Cloudflare D1):
--   * No cross-table FK constraints (D1 doesn't enforce them)
--   * Timestamps stored as TIMESTAMP (SQLite TEXT internally, ISO-8601)
--   * Booleans stored as INTEGER (0 = false, 1 = true)
--   * AUTOINCREMENT ensures monotonic IDs safe to use as cursor positions

CREATE TABLE skill_usage_events (
    id              INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    -- Skill identifier: matches the `name` field in skill front-matter
    -- (or the filename stem when front-matter is absent).
    skill_name      TEXT    NOT NULL,
    -- Wall-clock time when the skill was injected into the agent context.
    invoked_at      TIMESTAMP NOT NULL,
    -- Serialised orchestrator role (e.g. "Worker", "Planner", "Reviewer").
    role            TEXT    NOT NULL,
    -- LLM model slug used for the turn that consumed this skill
    -- (e.g. "dynamic/text_gen").  NULL when telemetry is unavailable.
    model_id        TEXT,
    -- Input tokens consumed by the turn.  NULL when telemetry is unavailable.
    tokens_in       INTEGER,
    -- Output tokens generated by the turn.  NULL when telemetry is unavailable.
    tokens_out      INTEGER,
    -- Number of tool calls made during the turn.
    tool_calls      INTEGER,
    -- 1 = the task that used this skill completed successfully, 0 = failed.
    success         INTEGER NOT NULL DEFAULT 1,
    -- Optional correlation identifiers for cross-system tracing.
    task_id         TEXT,
    conversation_id TEXT
);
