use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use remote_server::proto;

use crate::code_review::diff_size_limits::DiffSize;
use crate::code_review::diff_state::{
    DiffMetadata, DiffMetadataAgainstBase, DiffMode, DiffState, DiffStateModelEvent, DiffStats,
    GitDiffData, RemoteDiffStateModel,
};
use crate::util::git::{Commit, PrInfo};

use super::InternalRemoteDiffState;

// ── Helpers ─────────────────────────────────────────────────────────

fn empty_proto_metadata(branch: &str) -> proto::DiffMetadata {
    proto::DiffMetadata {
        main_branch_name: "main".to_string(),
        current_branch_name: branch.to_string(),
        against_head: Some(proto::DiffMetadataAgainstBase {
            aggregate_stats: Some(proto::DiffStats {
                files_changed: 0,
                total_additions: 0,
                total_deletions: 0,
            }),
        }),
        against_base_branch: None,
        has_head_commit: true,
        unpushed_commits: vec![],
        upstream_ref: None,
        pr_info: None,
    }
}

fn loaded_snapshot_with_files(files: Vec<proto::FileDiff>) -> proto::DiffStateSnapshot {
    let files_changed = files.len() as u64;
    proto::DiffStateSnapshot {
        repo_path: "/test/repo".to_string(),
        mode: Some(proto::DiffMode {
            mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
        }),
        metadata: Some(empty_proto_metadata("feature")),
        state: Some(proto::DiffState {
            state: Some(proto::diff_state::State::Loaded(proto::DiffStateLoaded {})),
        }),
        diffs: Some(proto::GitDiffData {
            files,
            total_additions: 1,
            total_deletions: 0,
            files_changed,
        }),
    }
}

fn simple_proto_file(path: &str) -> proto::FileDiff {
    simple_proto_file_with_content(path, None)
}

fn simple_proto_file_with_content(path: &str, content_at_base: Option<&str>) -> proto::FileDiff {
    proto::FileDiff {
        file_path: path.to_string(),
        status: Some(proto::GitFileStatus {
            status: Some(proto::git_file_status::Status::Modified(
                proto::GitFileStatusModified {},
            )),
        }),
        hunks: vec![proto::DiffHunk {
            old_start_line: 1,
            old_line_count: 1,
            new_start_line: 1,
            new_line_count: 2,
            lines: vec![proto::DiffLine {
                line_type: proto::DiffLineType::Add.into(),
                old_line_number: None,
                new_line_number: Some(2),
                text: "+new line".to_string(),
                no_trailing_newline: false,
            }],
            unified_diff_start: 0,
            unified_diff_end: 1,
        }],
        is_binary: false,
        is_autogenerated: false,
        max_line_number: 10,
        has_hidden_bidi_chars: false,
        size: proto::DiffSize::Normal.into(),
        content_at_base: content_at_base.map(str::to_string),
    }
}

fn test_metadata(branch: &str) -> DiffMetadata {
    DiffMetadata {
        main_branch_name: "main".to_string(),
        current_branch_name: branch.to_string(),
        against_head: DiffMetadataAgainstBase {
            aggregate_stats: DiffStats {
                files_changed: 1,
                total_additions: 5,
                total_deletions: 2,
            },
        },
        against_base_branch: None,
        has_head_commit: true,
        unpushed_commits: vec![Commit {
            hash: "abc123".to_string(),
            subject: "test commit".to_string(),
            files_changed: 1,
            additions: 5,
            deletions: 2,
        }],
        upstream_ref: Some("origin/feature".to_string()),
        pr_info: Some(PrInfo {
            number: 42,
            url: "https://github.com/test/repo/pull/42".to_string(),
        }),
    }
}

// ── apply_snapshot ──────────────────────────────────────────────────

#[test]
fn apply_snapshot_loaded_with_diffs() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let snapshot = loaded_snapshot_with_files(vec![simple_proto_file("src/main.rs")]);
        handle.update(&mut app, |m, ctx| m.apply_snapshot(&snapshot, ctx));
        handle.read(&app, |m, _| {
            assert!(matches!(m.get(), DiffState::Loaded));
            assert!(m.metadata.is_some());
        });
    });
}

#[test]
fn apply_snapshot_loaded_preserves_content_at_base_in_event() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let emitted_content = Arc::new(Mutex::new(Vec::new()));
        {
            let emitted_content = emitted_content.clone();
            app.update(|ctx| {
                ctx.subscribe_to_model(&handle, move |_, event, _| {
                    if let DiffStateModelEvent::NewDiffsComputed(Some(diffs)) = event {
                        emitted_content
                            .lock()
                            .expect("emitted content mutex should not be poisoned")
                            .push(
                                diffs
                                    .files
                                    .first()
                                    .and_then(|file| file.content_at_head.clone()),
                            );
                    }
                });
            });
        }

        let snapshot = loaded_snapshot_with_files(vec![simple_proto_file_with_content(
            "src/main.rs",
            Some("base content"),
        )]);
        handle.update(&mut app, |m, ctx| m.apply_snapshot(&snapshot, ctx));

        assert_eq!(
            emitted_content
                .lock()
                .expect("emitted content mutex should not be poisoned")
                .as_slice(),
            &[Some("base content".to_string())]
        );
    });
}

#[test]
fn apply_snapshot_loaded_without_diffs_becomes_error() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let snapshot = proto::DiffStateSnapshot {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            metadata: None,
            state: Some(proto::DiffState {
                state: Some(proto::diff_state::State::Loaded(proto::DiffStateLoaded {})),
            }),
            diffs: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_snapshot(&snapshot, ctx));
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Error(_)
        ));
    });
}

#[test]
fn apply_snapshot_not_in_repository() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let snapshot = proto::DiffStateSnapshot {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            metadata: None,
            state: Some(proto::DiffState {
                state: Some(proto::diff_state::State::NotInRepository(
                    proto::DiffStateNotInRepository {},
                )),
            }),
            diffs: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_snapshot(&snapshot, ctx));
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::NotInRepository
        ));
    });
}

#[test]
fn apply_snapshot_error_stores_message() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let snapshot = proto::DiffStateSnapshot {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            metadata: None,
            state: Some(proto::DiffState {
                state: Some(proto::diff_state::State::Error(
                    proto::DiffStateErrorValue {
                        message: "git failed".into(),
                    },
                )),
            }),
            diffs: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_snapshot(&snapshot, ctx));
        assert!(
            matches!(handle.read(&app, |m, _| m.get()), DiffState::Error(ref msg) if msg == "git failed")
        );
    });
}

// ── apply_metadata_update ───────────────────────────────────────────

#[test]
fn apply_metadata_first_time_sets_branch() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let proto_meta = empty_proto_metadata("feature");
        handle.update(&mut app, |m, ctx| m.apply_metadata_update(&proto_meta, ctx));
        assert_eq!(
            handle
                .read(&app, |m, _| m.get_current_branch_name())
                .as_deref(),
            Some("feature")
        );
    });
}

#[test]
fn apply_metadata_branch_change_updates_branch() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                Some(test_metadata("feature-a")),
            )
        });
        let proto_meta = empty_proto_metadata("feature-b");
        handle.update(&mut app, |m, ctx| m.apply_metadata_update(&proto_meta, ctx));
        assert_eq!(
            handle
                .read(&app, |m, _| m.get_current_branch_name())
                .as_deref(),
            Some("feature-b")
        );
    });
}

// ── apply_file_delta ────────────────────────────────────────────────

#[test]
fn apply_file_delta_ignored_when_not_loaded() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let delta = proto::DiffStateFileDelta {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            file_path: "src/main.rs".into(),
            diff: Some(simple_proto_file("src/main.rs")),
            metadata: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_file_delta(&delta, ctx));
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Loading
        ));
    });
}

#[test]
fn apply_file_delta_adds_file() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loaded(GitDiffData {
                    files: vec![],
                    total_additions: 0,
                    total_deletions: 0,
                    files_changed: 0,
                }),
                None,
            )
        });
        let delta = proto::DiffStateFileDelta {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            file_path: "src/new.rs".into(),
            diff: Some(simple_proto_file("src/new.rs")),
            metadata: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_file_delta(&delta, ctx));
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Loaded
        ));
    });
}

#[test]
fn apply_file_delta_preserves_content_at_base_in_event() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loaded(GitDiffData {
                    files: vec![],
                    total_additions: 0,
                    total_deletions: 0,
                    files_changed: 0,
                }),
                None,
            )
        });
        let emitted_content = Arc::new(Mutex::new(Vec::new()));
        {
            let emitted_content = emitted_content.clone();
            app.update(|ctx| {
                ctx.subscribe_to_model(&handle, move |_, event, _| {
                    if let DiffStateModelEvent::SingleFileUpdated {
                        diff: Some(diff), ..
                    } = event
                    {
                        emitted_content
                            .lock()
                            .expect("emitted content mutex should not be poisoned")
                            .push(diff.content_at_head.clone());
                    }
                });
            });
        }

        let delta = proto::DiffStateFileDelta {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            file_path: "src/new.rs".into(),
            diff: Some(simple_proto_file_with_content(
                "src/new.rs",
                Some("old file content"),
            )),
            metadata: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_file_delta(&delta, ctx));

        assert_eq!(
            emitted_content
                .lock()
                .expect("emitted content mutex should not be poisoned")
                .as_slice(),
            &[Some("old file content".to_string())]
        );
    });
}

#[test]
fn apply_file_delta_none_removes_file() {
    warpui::App::test((), |mut app| async move {
        let existing = GitDiffData {
            files: vec![crate::code_review::diff_state::FileDiff {
                file_path: PathBuf::from("src/old.rs"),
                status: crate::code_review::diff_state::GitFileStatus::Modified,
                hunks: Arc::new(vec![]),
                is_binary: false,
                is_autogenerated: false,
                max_line_number: 0,
                has_hidden_bidi_chars: false,
                size: DiffSize::Normal,
            }],
            total_additions: 0,
            total_deletions: 0,
            files_changed: 1,
        };
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loaded(existing),
                None,
            )
        });
        let delta = proto::DiffStateFileDelta {
            repo_path: "/test/repo".into(),
            mode: Some(proto::DiffMode {
                mode: Some(proto::diff_mode::Mode::Head(proto::DiffModeHead {})),
            }),
            file_path: "src/old.rs".into(),
            diff: None,
            metadata: None,
        };
        handle.update(&mut app, |m, ctx| m.apply_file_delta(&delta, ctx));
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Loaded
        ));
    });
}

// ── Read API ────────────────────────────────────────────────────────

#[test]
fn read_api_with_metadata() {
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::Head,
        InternalRemoteDiffState::Loading,
        Some(test_metadata("feature")),
    );
    assert_eq!(m.get_main_branch_name().as_deref(), Some("main"));
    assert_eq!(m.get_current_branch_name().as_deref(), Some("feature"));
    assert!(!m.is_on_main_branch());
    assert_eq!(m.unpushed_commits().len(), 1);
    assert_eq!(m.upstream_ref(), Some("origin/feature"));
    assert!(m.upstream_differs_from_main());
    assert_eq!(m.pr_info().unwrap().number, 42);
    assert!(m.has_head());
    assert_eq!(m.get_uncommitted_stats().unwrap().total_additions, 5);
}

#[test]
fn read_api_defaults_without_metadata() {
    let m =
        RemoteDiffStateModel::new_for_test(DiffMode::Head, InternalRemoteDiffState::Loading, None);
    assert_eq!(m.get_main_branch_name(), None);
    assert_eq!(m.get_current_branch_name(), None);
    assert!(!m.is_on_main_branch());
    assert!(m.unpushed_commits().is_empty());
    assert!(m.upstream_ref().is_none());
    assert!(!m.upstream_differs_from_main());
    assert!(m.pr_info().is_none());
    assert!(!m.has_head());
    assert!(m.get_uncommitted_stats().is_none());
}

#[test]
fn is_on_main_branch_true_when_matching() {
    let mut meta = test_metadata("main");
    meta.current_branch_name = "main".into();
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::Head,
        InternalRemoteDiffState::Loading,
        Some(meta),
    );
    assert!(m.is_on_main_branch());
}

#[test]
fn get_returns_each_state_variant() {
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(DiffMode::Head, InternalRemoteDiffState::Loading, None)
            .get(),
        DiffState::Loading
    ));
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(
            DiffMode::Head,
            InternalRemoteDiffState::NotInRepository,
            None
        )
        .get(),
        DiffState::NotInRepository
    ));
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(
            DiffMode::Head,
            InternalRemoteDiffState::Error("x".into()),
            None
        )
        .get(),
        DiffState::Error(_)
    ));
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(
            DiffMode::Head,
            InternalRemoteDiffState::Disconnected,
            None
        )
        .get(),
        DiffState::Disconnected
    ));
}

#[test]
fn diff_mode_preserved() {
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::OtherBranch("develop".into()),
        InternalRemoteDiffState::Loading,
        None,
    );
    assert_eq!(m.diff_mode(), DiffMode::OtherBranch("develop".into()));
}

#[test]
fn empty_branch_names_become_none() {
    let mut meta = test_metadata("");
    meta.main_branch_name = String::new();
    meta.current_branch_name = String::new();
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::Head,
        InternalRemoteDiffState::Loading,
        Some(meta),
    );
    assert_eq!(m.get_main_branch_name(), None);
    assert_eq!(m.get_current_branch_name(), None);
}
