use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use warp_core::SessionId;
use warp_util::remote_path::RemotePath;
use warp_util::standardized_path::StandardizedPath;

use crate::code_review::diff_size_limits::DiffSize;
use crate::code_review::diff_state::{
    DiffHunk, DiffLine, DiffLineType, DiffMetadata, DiffMetadataAgainstBase, DiffMode, DiffState,
    DiffStateModelEvent, DiffStats, FileDiff, FileDiffAndContent, GitDiffData,
    GitDiffWithBaseContent, GitFileStatus, RemoteDiffStateModel,
};
use crate::util::git::{Commit, PrInfo};

use super::InternalRemoteDiffState;

impl RemoteDiffStateModel {
    fn new_for_test(
        mode: DiffMode,
        state: InternalRemoteDiffState,
        metadata: Option<DiffMetadata>,
    ) -> Self {
        Self {
            remote_path: RemotePath::new(
                remote_server::HostId::new("test-host".to_string()),
                warp_util::standardized_path::StandardizedPath::try_new("/test/repo")
                    .expect("test repo path should be valid and absolute"),
            ),
            mode,
            session_id: SessionId::default(),
            state,
            metadata,
        }
    }
}

fn test_path(path: &str) -> StandardizedPath {
    StandardizedPath::try_new(path).expect("test path should be valid and absolute")
}

fn empty_metadata(branch: &str) -> DiffMetadata {
    DiffMetadata {
        main_branch_name: "main".to_string(),
        current_branch_name: branch.to_string(),
        against_head: DiffMetadataAgainstBase {
            aggregate_stats: DiffStats::default(),
        },
        against_base_branch: None,
        has_head_commit: true,
        unpushed_commits: vec![],
        upstream_ref: None,
        pr_info: None,
    }
}

/// Snapshot inputs grouped for ergonomic test construction. Mirrors the
/// argument list of `RemoteDiffStateModel::apply_snapshot`.
struct SnapshotInputs {
    metadata: Option<DiffMetadata>,
    state: DiffState,
    diffs: Option<GitDiffWithBaseContent>,
}

fn loaded_snapshot_with_files(files: Vec<FileDiffAndContent>) -> SnapshotInputs {
    let files_changed = files.len();
    SnapshotInputs {
        metadata: Some(empty_metadata("feature")),
        state: DiffState::Loaded,
        diffs: Some(GitDiffWithBaseContent {
            files,
            total_additions: 1,
            total_deletions: 0,
            files_changed,
        }),
    }
}

fn simple_file(path: &str) -> FileDiffAndContent {
    simple_file_with_content(path, None)
}

fn simple_file_with_content(path: &str, content_at_base: Option<&str>) -> FileDiffAndContent {
    FileDiffAndContent {
        file_diff: FileDiff {
            file_path: PathBuf::from(path),
            status: GitFileStatus::Modified,
            hunks: Arc::new(vec![DiffHunk {
                old_start_line: 1,
                old_line_count: 1,
                new_start_line: 1,
                new_line_count: 2,
                lines: vec![DiffLine {
                    line_type: DiffLineType::Add,
                    old_line_number: None,
                    new_line_number: Some(2),
                    text: "+new line".to_string(),
                    no_trailing_newline: false,
                }],
                unified_diff_start: 0,
                unified_diff_end: 1,
            }]),
            is_binary: false,
            is_autogenerated: false,
            max_line_number: 10,
            has_hidden_bidi_chars: false,
            size: DiffSize::Normal,
        },
        content_at_head: content_at_base.map(str::to_string),
    }
}

fn test_metadata(branch: &str) -> DiffMetadata {
    DiffMetadata {
        main_branch_name: "main".to_string(),
        current_branch_name: branch.to_string(),
        against_head: DiffMetadataAgainstBase {
            aggregate_stats: DiffStats {
                files_changed: 1,
                total_additions: 5,
                total_deletions: 2,
            },
        },
        against_base_branch: None,
        has_head_commit: true,
        unpushed_commits: vec![Commit {
            hash: "abc123".to_string(),
            subject: "test commit".to_string(),
            files_changed: 1,
            additions: 5,
            deletions: 2,
        }],
        upstream_ref: Some("origin/feature".to_string()),
        pr_info: Some(PrInfo {
            number: 42,
            url: "https://github.com/test/repo/pull/42".to_string(),
        }),
    }
}

#[test]
fn apply_snapshot_loaded_with_diffs() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let SnapshotInputs {
            metadata,
            state,
            diffs,
        } = loaded_snapshot_with_files(vec![simple_file("/test/repo/src/main.rs")]);
        handle.update(&mut app, |m, ctx| {
            m.apply_snapshot(metadata, state, diffs, ctx)
        });
        handle.read(&app, |m, _| {
            assert!(matches!(m.get(), DiffState::Loaded));
            assert!(m.metadata.is_some());
        });
    });
}

#[test]
fn apply_snapshot_loaded_preserves_content_at_base_in_event() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let emitted_content = Arc::new(Mutex::new(Vec::new()));
        {
            let emitted_content = emitted_content.clone();
            app.update(|ctx| {
                ctx.subscribe_to_model(&handle, move |_, event, _| {
                    if let DiffStateModelEvent::NewDiffsComputed(Some(diffs)) = event {
                        emitted_content
                            .lock()
                            .expect("emitted content mutex should not be poisoned")
                            .push(
                                diffs
                                    .files
                                    .first()
                                    .and_then(|file| file.content_at_head.clone()),
                            );
                    }
                });
            });
        }

        let SnapshotInputs {
            metadata,
            state,
            diffs,
        } = loaded_snapshot_with_files(vec![simple_file_with_content(
            "/test/repo/src/main.rs",
            Some("base content"),
        )]);
        handle.update(&mut app, |m, ctx| {
            m.apply_snapshot(metadata, state, diffs, ctx)
        });

        assert_eq!(
            emitted_content
                .lock()
                .expect("emitted content mutex should not be poisoned")
                .as_slice(),
            &[Some("base content".to_string())]
        );
    });
}

#[test]
fn apply_snapshot_loaded_without_diffs_becomes_error() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        handle.update(&mut app, |m, ctx| {
            m.apply_snapshot(None, DiffState::Loaded, None, ctx)
        });
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Error(_)
        ));
    });
}

#[test]
fn apply_snapshot_not_in_repository() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        handle.update(&mut app, |m, ctx| {
            m.apply_snapshot(None, DiffState::NotInRepository, None, ctx)
        });
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::NotInRepository
        ));
    });
}

#[test]
fn apply_snapshot_error_stores_message() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        handle.update(&mut app, |m, ctx| {
            m.apply_snapshot(None, DiffState::Error("git failed".to_string()), None, ctx)
        });
        assert!(
            matches!(handle.read(&app, |m, _| m.get()), DiffState::Error(ref msg) if msg == "git failed")
        );
    });
}

#[test]
fn mark_disconnected_transitions_state_and_emits_connection_lost() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let connection_lost_count = Arc::new(Mutex::new(0));
        {
            let connection_lost_count = connection_lost_count.clone();
            app.update(|ctx| {
                ctx.subscribe_to_model(&handle, move |_, event, _| {
                    if matches!(event, DiffStateModelEvent::ConnectionLost) {
                        *connection_lost_count
                            .lock()
                            .expect("connection lost count mutex should not be poisoned") += 1;
                    }
                });
            });
        }

        handle.update(&mut app, |m, ctx| m.mark_disconnected(ctx));

        handle.read(&app, |m, _| {
            assert!(matches!(m.get(), DiffState::Disconnected));
        });
        assert_eq!(
            *connection_lost_count
                .lock()
                .expect("connection lost count mutex should not be poisoned"),
            1
        );

        // Idempotent: a second call should not re-emit ConnectionLost.
        handle.update(&mut app, |m, ctx| m.mark_disconnected(ctx));
        assert_eq!(
            *connection_lost_count
                .lock()
                .expect("connection lost count mutex should not be poisoned"),
            1
        );
    });
}

#[test]
fn apply_metadata_first_time_sets_branch() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let meta = empty_metadata("feature");
        handle.update(&mut app, |m, ctx| m.apply_metadata_update(&meta, ctx));
        assert_eq!(
            handle
                .read(&app, |m, _| m.get_current_branch_name())
                .as_deref(),
            Some("feature")
        );
    });
}

#[test]
fn apply_metadata_branch_change_updates_branch() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                Some(test_metadata("feature-a")),
            )
        });
        let meta = empty_metadata("feature-b");
        handle.update(&mut app, |m, ctx| m.apply_metadata_update(&meta, ctx));
        assert_eq!(
            handle
                .read(&app, |m, _| m.get_current_branch_name())
                .as_deref(),
            Some("feature-b")
        );
    });
}

#[test]
fn apply_file_delta_ignored_when_not_loaded() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loading,
                None,
            )
        });
        let file_path = test_path("/test/repo/src/main.rs");
        let diff = Some(simple_file("/test/repo/src/main.rs"));
        handle.update(&mut app, |m, ctx| {
            m.apply_file_delta(file_path, diff, None, ctx)
        });
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Loading
        ));
    });
}

#[test]
fn apply_file_delta_adds_file() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loaded(GitDiffData {
                    files: vec![],
                    total_additions: 0,
                    total_deletions: 0,
                    files_changed: 0,
                }),
                None,
            )
        });
        let file_path = test_path("/test/repo/src/new.rs");
        let diff = Some(simple_file("/test/repo/src/new.rs"));
        handle.update(&mut app, |m, ctx| {
            m.apply_file_delta(file_path, diff, None, ctx)
        });
        assert!(matches!(
            handle.read(&app, |m, _| m.get()),
            DiffState::Loaded
        ));
    });
}

#[test]
fn apply_file_delta_preserves_content_at_base_in_event() {
    warpui::App::test((), |mut app| async move {
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loaded(GitDiffData {
                    files: vec![],
                    total_additions: 0,
                    total_deletions: 0,
                    files_changed: 0,
                }),
                None,
            )
        });
        let emitted_content = Arc::new(Mutex::new(Vec::new()));
        {
            let emitted_content = emitted_content.clone();
            app.update(|ctx| {
                ctx.subscribe_to_model(&handle, move |_, event, _| {
                    if let DiffStateModelEvent::SingleFileUpdated {
                        diff: Some(diff), ..
                    } = event
                    {
                        emitted_content
                            .lock()
                            .expect("emitted content mutex should not be poisoned")
                            .push(diff.content_at_head.clone());
                    }
                });
            });
        }

        let file_path = test_path("/test/repo/src/new.rs");
        let diff = Some(simple_file_with_content(
            "/test/repo/src/new.rs",
            Some("old file content"),
        ));
        handle.update(&mut app, |m, ctx| {
            m.apply_file_delta(file_path, diff, None, ctx)
        });

        assert_eq!(
            emitted_content
                .lock()
                .expect("emitted content mutex should not be poisoned")
                .as_slice(),
            &[Some("old file content".to_string())]
        );
    });
}

#[test]
fn apply_file_delta_none_removes_file() {
    warpui::App::test((), |mut app| async move {
        let existing = GitDiffData {
            files: vec![FileDiff {
                file_path: PathBuf::from("/test/repo/src/old.rs"),
                status: GitFileStatus::Modified,
                hunks: Arc::new(vec![]),
                is_binary: false,
                is_autogenerated: false,
                max_line_number: 0,
                has_hidden_bidi_chars: false,
                size: DiffSize::Normal,
            }],
            total_additions: 0,
            total_deletions: 0,
            files_changed: 1,
        };
        let handle = app.add_model(|_ctx| {
            RemoteDiffStateModel::new_for_test(
                DiffMode::Head,
                InternalRemoteDiffState::Loaded(existing),
                None,
            )
        });
        let file_path = test_path("/test/repo/src/old.rs");
        handle.update(&mut app, |m, ctx| {
            m.apply_file_delta(file_path, None, None, ctx)
        });
        handle.read(&app, |m, _| {
            let InternalRemoteDiffState::Loaded(diffs) = &m.state else {
                panic!("state should remain loaded");
            };
            assert!(diffs.files.is_empty());
        });
    });
}

#[test]
fn read_api_with_metadata() {
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::Head,
        InternalRemoteDiffState::Loading,
        Some(test_metadata("feature")),
    );
    assert_eq!(m.get_main_branch_name().as_deref(), Some("main"));
    assert_eq!(m.get_current_branch_name().as_deref(), Some("feature"));
    assert!(!m.is_on_main_branch());
    assert_eq!(m.unpushed_commits().len(), 1);
    assert_eq!(m.upstream_ref(), Some("origin/feature"));
    assert!(m.upstream_differs_from_main());
    assert_eq!(m.pr_info().expect("pr info should be present").number, 42);
    assert!(m.has_head());
    assert_eq!(
        m.get_uncommitted_stats()
            .expect("uncommitted stats should be present")
            .total_additions,
        5
    );
}

#[test]
fn read_api_defaults_without_metadata() {
    let m =
        RemoteDiffStateModel::new_for_test(DiffMode::Head, InternalRemoteDiffState::Loading, None);
    assert_eq!(m.get_main_branch_name(), None);
    assert_eq!(m.get_current_branch_name(), None);
    assert!(!m.is_on_main_branch());
    assert!(m.unpushed_commits().is_empty());
    assert!(m.upstream_ref().is_none());
    assert!(!m.upstream_differs_from_main());
    assert!(m.pr_info().is_none());
    assert!(!m.has_head());
    assert!(m.get_uncommitted_stats().is_none());
}

#[test]
fn is_on_main_branch_true_when_matching() {
    let mut meta = test_metadata("main");
    meta.current_branch_name = "main".into();
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::Head,
        InternalRemoteDiffState::Loading,
        Some(meta),
    );
    assert!(m.is_on_main_branch());
}

#[test]
fn get_returns_each_state_variant() {
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(DiffMode::Head, InternalRemoteDiffState::Loading, None)
            .get(),
        DiffState::Loading
    ));
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(
            DiffMode::Head,
            InternalRemoteDiffState::NotInRepository,
            None
        )
        .get(),
        DiffState::NotInRepository
    ));
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(
            DiffMode::Head,
            InternalRemoteDiffState::Error("x".into()),
            None
        )
        .get(),
        DiffState::Error(_)
    ));
    assert!(matches!(
        RemoteDiffStateModel::new_for_test(
            DiffMode::Head,
            InternalRemoteDiffState::Disconnected,
            None
        )
        .get(),
        DiffState::Disconnected
    ));
}

#[test]
fn diff_mode_preserved() {
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::OtherBranch("develop".into()),
        InternalRemoteDiffState::Loading,
        None,
    );
    assert_eq!(m.diff_mode(), DiffMode::OtherBranch("develop".into()));
}

#[test]
fn empty_branch_names_become_none() {
    let mut meta = test_metadata("");
    meta.main_branch_name = String::new();
    meta.current_branch_name = String::new();
    let m = RemoteDiffStateModel::new_for_test(
        DiffMode::Head,
        InternalRemoteDiffState::Loading,
        Some(meta),
    );
    assert_eq!(m.get_main_branch_name(), None);
    assert_eq!(m.get_current_branch_name(), None);
}
