use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
#[cfg(feature = "local_fs")]
use toml::Value;

/// Describes a tab config file that failed to parse.
///
/// Carries enough context to surface a helpful, persistent error toast
/// so the user can locate and fix the broken TOML.
#[derive(Clone, Debug)]
pub struct TabConfigError {
    /// The file name shown in the toast (e.g. `"my_config.toml"`).
    pub file_name: String,
    /// Full path used by the "Open file" action.
    pub file_path: PathBuf,
    /// The full, untruncated error from `toml` deserialization.
    pub error_message: String,
}

fn contains_autogenerated_branch_name(value: &str) -> bool {
    value.contains(AUTOGENERATED_BRANCH_NAME_PARAM)
}

use crate::launch_configs::launch_config::{
    CommandTemplate, PaneMode, PaneTemplateType, SplitDirection,
};
use crate::themes::theme::AnsiColorIdentifier;

pub(crate) const AUTOGENERATED_BRANCH_NAME_PARAM: &str = "autogenerated_branch_name";

// Rust `format!` treats `{...}` as interpolation syntax, so we escape braces
// to emit the literal Handlebars placeholder `{{name}}` for the later
// tab-config render pass. In `format!("{{{{{name}}}}}")`, the outer doubled
// braces become literal `{` / `}`, and `{name}` interpolates the helper arg.
#[cfg(feature = "local_fs")]
fn handlebars_placeholder(name: &str) -> String {
    format!("{{{{{name}}}}}")
}

pub(crate) fn generated_worktree_repo_dir(repo_path: &Path) -> PathBuf {
    let repo_name = repo_path
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("untitled");
    warp_core::paths::data_dir()
        .join("worktrees")
        .join(repo_name)
}
pub(crate) fn generated_worktree_path(repo_path: &Path, worktree_name: &str) -> PathBuf {
    generated_worktree_repo_dir(repo_path).join(worktree_name)
}
pub(crate) fn generated_worktree_path_string(repo_path: &Path, worktree_name: &str) -> String {
    generated_worktree_path(repo_path, worktree_name)
        .display()
        .to_string()
}

/// The kind of smart picker to show for a parameter.
///
/// Authors opt in via `type = "branch"` or `type = "repo"` in the TOML.
/// Omitting the field (or using `type = "text"`) gives a plain text editor.
#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TabConfigParamType {
    /// A plain single-line text editor (the default).
    #[default]
    Text,
    /// A dropdown populated with local git branches from the active terminal's repo.
    Branch,
    /// A dropdown populated with known repos (from the project list), with an option to add a new one.
    Repo,
}

/// A single parameter declared in a tab config file.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TabConfigParam {
    /// Human-readable description shown in the param-fill UI.
    #[serde(default)]
    pub description: Option<String>,
    /// Default value used when the user provides no input.
    #[serde(default)]
    pub default: Option<String>,
    /// Controls which smart picker to render for this param.
    ///
    /// Defaults to `TabConfigParamType::Text` (a plain text input).
    #[serde(default, rename = "type")]
    pub param_type: TabConfigParamType,
}

// ── Flat pane schema ────────────────────────────────────────────────

/// The pane type declared on leaf nodes via `type = "..."` in TOML.
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TabConfigPaneType {
    /// A standard terminal shell session.
    Terminal,
    /// A terminal that immediately enters Agent Mode.
    Agent,
    /// A cloud-mode (ambient agent) pane with no local shell.
    Cloud,
}

/// A single node in the flat `[[panes]]` array.  Distinguished as a split vs.
/// leaf by the presence of `split` + `children`.
///
/// Leaf panes must specify `type` to indicate whether they open as a terminal,
/// agent, or cloud pane.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TabConfigPaneNode {
    pub id: String,

    /// The pane type. Required on leaf nodes; ignored on split nodes.
    #[serde(rename = "type")]
    pub pane_type: Option<TabConfigPaneType>,

    // -- Split fields (present for branches) --
    pub split: Option<SplitDirection>,
    pub children: Option<Vec<String>>,

    // -- Leaf fields --
    pub is_focused: Option<bool>,
    pub directory: Option<String>,
    pub commands: Option<Vec<String>>,
    /// Optional shell to use for this pane (e.g. `"pwsh"`, `"zsh"`, `"bash"`, `"fish"`).
    /// Only applies to `terminal` and `agent` pane types.
    /// If omitted or the shell is not found, the user's default shell is used.
    pub shell: Option<String>,
}

// ── TabConfig ───────────────────────────────────────────────────────

/// A tab config loaded from a `.toml` file in `~/.warp/tab_configs/`.
///
/// Pane layout is defined with a flat `[[panes]]` array where the first entry
/// is the root and splits reference children by ID.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TabConfig {
    /// Display name shown in the + menu.
    pub name: String,
    /// Optional tab title template. Supports `{{ }}` template variables.
    #[serde(default)]
    pub title: Option<String>,
    /// Optional tab color.
    #[serde(default)]
    pub color: Option<AnsiColorIdentifier>,
    /// Flat pane list. The first entry is the root of the pane tree.
    #[serde(default)]
    pub panes: Vec<TabConfigPaneNode>,
    /// Named parameters that the user fills in before the tab opens.
    /// Keys are parameter names (used in `{{ }}` placeholders).
    #[serde(default)]
    pub params: HashMap<String, TabConfigParam>,
    /// The on-disk path this config was loaded from.
    /// Populated during parsing; not serialized into or from the TOML.
    #[serde(skip)]
    pub source_path: Option<PathBuf>,
}

impl TabConfig {
    /// Returns param values using defaults where available, and empty strings for
    /// params with no default.  This is the fallback used when no param-fill UI is shown.
    pub fn default_param_values(&self) -> HashMap<String, String> {
        self.params
            .iter()
            .map(|(name, param)| {
                let value = param.default.clone().unwrap_or_default();
                (name.clone(), value)
            })
            .collect()
    }

    pub(crate) fn is_worktree(&self) -> bool {
        self.panes.iter().any(|pane| {
            pane.commands.as_ref().is_some_and(|commands| {
                commands
                    .iter()
                    .any(|command| command.contains("git worktree"))
            })
        })
    }

    pub(crate) fn uses_autogenerated_branch_name(&self) -> bool {
        self.title
            .as_deref()
            .is_some_and(contains_autogenerated_branch_name)
            || self.panes.iter().any(|pane| {
                pane.directory
                    .as_deref()
                    .is_some_and(contains_autogenerated_branch_name)
                    || pane.commands.as_ref().is_some_and(|commands| {
                        commands
                            .iter()
                            .any(|command| contains_autogenerated_branch_name(command))
                    })
            })
    }
}

/// Renders a [`TabConfig`] with the given param values into a [`PaneTemplateType`]
/// and an optional rendered title.
///
/// - `title` and `directory` receive unquoted param values (quoting would break paths).
/// - `commands` receive shell-quoted param values to prevent injection.
/// - `worktree_branch_name`: when `Some`, injected into the template context as the
///   special-cased `autogenerated_branch_name` var so commands can use
///   `{{autogenerated_branch_name}}`.
pub fn render_tab_config(
    config: &TabConfig,
    param_values: &HashMap<String, String>,
    worktree_branch_name: Option<&str>,
) -> (Option<String>, PaneTemplateType) {
    let (unquoted_context, quoted_context) =
        build_template_contexts(param_values, worktree_branch_name);

    let rendered_title = config
        .title
        .as_deref()
        .map(|t| handlebars::render_template(t, &unquoted_context));

    let pane_template = match resolve_pane_tree(&config.panes, &unquoted_context, &quoted_context) {
        Ok(template) => template,
        Err(err) => {
            log::warn!("Failed to resolve pane tree for '{}': {err}", config.name);
            PaneTemplateType::PaneTemplate {
                cwd: PathBuf::new(),
                commands: Vec::new(),
                is_focused: Some(true),
                pane_mode: PaneMode::Terminal,
                shell: None,
            }
        }
    };

    (rendered_title, pane_template)
}

fn build_template_contexts(
    param_values: &HashMap<String, String>,
    worktree_branch_name: Option<&str>,
) -> (HashMap<String, String>, HashMap<String, String>) {
    let mut unquoted_context = param_values.clone();
    let mut quoted_context: HashMap<String, String> = param_values
        .iter()
        .map(|(k, v)| (k.clone(), shell_words::quote(v).into_owned()))
        .collect();

    if let Some(name) = worktree_branch_name {
        unquoted_context.insert(
            AUTOGENERATED_BRANCH_NAME_PARAM.to_string(),
            name.to_string(),
        );
        quoted_context.insert(
            AUTOGENERATED_BRANCH_NAME_PARAM.to_string(),
            shell_words::quote(name).into_owned(),
        );
    }

    (unquoted_context, quoted_context)
}

// ── Flat pane tree resolution ───────────────────────────────────────

/// Builds a [`PaneTemplateType`] tree from a flat `[[panes]]` list.
///
/// The first entry is the root.  Split nodes reference children by ID;
/// leaf nodes produce terminal panes.
fn resolve_pane_tree(
    panes: &[TabConfigPaneNode],
    unquoted: &HashMap<String, String>,
    quoted: &HashMap<String, String>,
) -> Result<PaneTemplateType, String> {
    if panes.is_empty() {
        return Err("panes array is empty".to_string());
    }

    let pane_map: HashMap<&str, &TabConfigPaneNode> =
        panes.iter().map(|p| (p.id.as_str(), p)).collect();

    if pane_map.len() != panes.len() {
        return Err("duplicate pane IDs detected".to_string());
    }

    let root = &panes[0];
    let has_explicit_focus = panes
        .iter()
        .any(|p| p.split.is_none() && p.is_focused == Some(true));

    let (template, _) = resolve_pane_node(
        root,
        &pane_map,
        unquoted,
        quoted,
        !has_explicit_focus, // auto-focus first leaf when nothing is explicitly focused
    )?;

    Ok(template)
}

/// Recursively resolves a single pane node.
///
/// Returns `(PaneTemplateType, did_consume_auto_focus)` — the second element
/// is `true` when a leaf consumed the auto-focus so subsequent leaves are not
/// also focused.
fn resolve_pane_node(
    node: &TabConfigPaneNode,
    pane_map: &HashMap<&str, &TabConfigPaneNode>,
    unquoted: &HashMap<String, String>,
    quoted: &HashMap<String, String>,
    auto_focus_first_leaf: bool,
) -> Result<(PaneTemplateType, bool), String> {
    if let Some(split_direction) = &node.split {
        // ── Split node ──────────────────────────────────────────────
        let children = node
            .children
            .as_ref()
            .ok_or_else(|| format!("split node '{}' is missing 'children'", node.id))?;

        if children.len() < 2 {
            return Err(format!(
                "split node '{}' must have at least 2 children, got {}",
                node.id,
                children.len()
            ));
        }

        let mut child_templates = Vec::with_capacity(children.len());
        let mut auto_focus_remaining = auto_focus_first_leaf;

        for child_id in children {
            let child = pane_map.get(child_id.as_str()).ok_or_else(|| {
                format!(
                    "split node '{}' references unknown child '{}'",
                    node.id, child_id
                )
            })?;
            let (child_template, did_focus) =
                resolve_pane_node(child, pane_map, unquoted, quoted, auto_focus_remaining)?;
            if did_focus {
                auto_focus_remaining = false;
            }
            child_templates.push(child_template);
        }

        Ok((
            PaneTemplateType::PaneBranchTemplate {
                split_direction: split_direction.clone(),
                panes: child_templates,
            },
            auto_focus_first_leaf && !auto_focus_remaining,
        ))
    } else {
        // ── Leaf node ────────────────────────────────────────────────
        let pane_type = node
            .pane_type
            .as_ref()
            .ok_or_else(|| format!("leaf pane '{}' is missing required 'type' field", node.id))?;

        let pane_mode = match pane_type {
            TabConfigPaneType::Terminal => PaneMode::Terminal,
            TabConfigPaneType::Agent => PaneMode::Agent,
            TabConfigPaneType::Cloud => PaneMode::Cloud,
        };

        let cwd = node
            .directory
            .as_deref()
            .map(|c| {
                let rendered = handlebars::render_template(c, unquoted);
                PathBuf::from(shellexpand::tilde(&rendered).into_owned())
            })
            .unwrap_or_default();

        let commands: Vec<CommandTemplate> = node
            .commands
            .as_ref()
            .map(|cmds| {
                cmds.iter()
                    .map(|cmd| CommandTemplate {
                        exec: handlebars::render_template(cmd, quoted),
                    })
                    .collect()
            })
            .unwrap_or_default();

        let explicitly_focused = node.is_focused == Some(true);
        let is_focused = explicitly_focused || auto_focus_first_leaf;
        let did_consume = is_focused && !explicitly_focused;

        Ok((
            PaneTemplateType::PaneTemplate {
                cwd,
                commands,
                is_focused: Some(is_focused),
                pane_mode,
                shell: node.shell.clone(),
            },
            explicitly_focused || did_consume,
        ))
    }
}

/// Builds a worktree tab config TOML string.
///
/// When `worktree_branch_name` is `Some(name)` (manual naming), the returned
/// TOML bakes commands with Handlebars template variables and exposes a
/// `worktree_branch_name` param so re-opens show the params modal.
///
/// When `None` (autogenerate), the TOML stores commands with
/// `{{autogenerated_branch_name}}` Handlebars template variables that get
/// substituted with a fresh name on every open.
#[cfg(feature = "local_fs")]
pub(crate) fn build_worktree_config_toml(
    config_name: &str,
    repo: &str,
    base_branch: &str,
    worktree_branch_name: Option<&str>,
) -> String {
    let mut doc = toml::map::Map::new();
    doc.insert("name".into(), Value::String(config_name.to_string()));

    let mut pane = toml::map::Map::new();
    pane.insert("id".into(), Value::String("main".into()));
    pane.insert("type".into(), Value::String("terminal".into()));
    pane.insert("directory".into(), Value::String(repo.to_string()));

    if worktree_branch_name.is_some() {
        let worktree_branch_name = handlebars_placeholder("worktree_branch_name");
        let worktree_path = generated_worktree_path_string(Path::new(repo), &worktree_branch_name);
        doc.insert("title".into(), Value::String(worktree_branch_name.clone()));
        pane.insert(
            "commands".into(),
            Value::Array(vec![
                Value::String(format!(
                    "git worktree add -b {worktree_branch_name} {worktree_path} {base_branch}"
                )),
                Value::String(format!("cd {worktree_path}")),
            ]),
        );
        doc.insert("panes".into(), Value::Array(vec![Value::Table(pane)]));

        let mut param = toml::map::Map::new();
        param.insert("type".into(), Value::String("text".into()));
        param.insert(
            "description".into(),
            Value::String("Worktree branch name".to_string()),
        );
        let mut params = toml::map::Map::new();
        params.insert("worktree_branch_name".into(), Value::Table(param));
        doc.insert("params".into(), Value::Table(params));
    } else {
        let autogenerated_branch_name = handlebars_placeholder(AUTOGENERATED_BRANCH_NAME_PARAM);
        let worktree_path =
            generated_worktree_path_string(Path::new(repo), &autogenerated_branch_name);
        pane.insert(
            "commands".into(),
            Value::Array(vec![
                Value::String(format!(
                    "git worktree add -b {autogenerated_branch_name} {worktree_path} {base_branch}"
                )),
                Value::String(format!("cd {worktree_path}")),
            ]),
        );
        doc.insert("panes".into(), Value::Array(vec![Value::Table(pane)]));
    }

    toml::to_string_pretty(&Value::Table(doc)).expect("generated TOML should always serialize")
}

#[cfg(test)]
#[path = "tab_config_tests.rs"]
mod tests;
