//! Append-only write path for skill usage events (PDX-71).
//!
//! Call [`Ledger::append`] after each skill invocation to record a
//! [`UsageEvent`].  The write goes directly to the local SQLite database;
//! the connection is shared with the rest of the app so no extra file is
//! opened.
//!
//! The table schema is designed to be mirrored verbatim to Cloudflare D1 in
//! phase C (PDX-22).  Callers should treat ledger errors as non-fatal and log
//! them rather than propagating them up the hot path.

use chrono::Utc;
use diesel::{prelude::*, SqliteConnection};
use persistence::{model::NewSkillUsageEvent, schema::skill_usage_events};
use thiserror::Error;

// ── Public types ─────────────────────────────────────────────────────────────

/// A single skill invocation to record.
#[derive(Debug, Clone)]
pub struct UsageEvent {
    /// Skill name as it appears in front-matter (or the filename stem).
    pub skill_name: String,
    /// Serialised orchestrator role (e.g. `"Worker"`, `"Planner"`).
    pub role: String,
    /// LLM model slug used during the turn (e.g. `"dynamic/text_gen"`).
    /// `None` when telemetry is unavailable.
    pub model_id: Option<String>,
    /// Input tokens consumed by the turn.
    pub tokens_in: Option<i32>,
    /// Output tokens generated by the turn.
    pub tokens_out: Option<i32>,
    /// Number of tool calls made during the turn.
    pub tool_calls: Option<i32>,
    /// `true` if the task that used this skill completed successfully.
    pub success: bool,
    /// Optional task correlation ID for cross-system tracing.
    pub task_id: Option<String>,
    /// Optional conversation correlation ID.
    pub conversation_id: Option<String>,
}

/// Errors produced by ledger writes.
#[derive(Debug, Error)]
pub enum LedgerError {
    #[error("sqlite write failed: {0}")]
    Diesel(String),
}

// ── Ledger ───────────────────────────────────────────────────────────────────

/// Append-only write proxy for the `skill_usage_events` table.
///
/// Borrows an existing [`SqliteConnection`] so it participates in the same
/// connection lifecycle as the rest of the app.
pub struct Ledger<'conn> {
    conn: &'conn mut SqliteConnection,
}

impl<'conn> Ledger<'conn> {
    /// Wrap an existing connection.
    pub fn new(conn: &'conn mut SqliteConnection) -> Self {
        Self { conn }
    }

    /// Append one skill invocation record.
    ///
    /// The `invoked_at` timestamp is set to `Utc::now()` at call time.
    /// Returns [`LedgerError`] only on a genuine database failure; callers
    /// are encouraged to log and discard the error to keep the hot path clean.
    pub fn append(&mut self, event: UsageEvent) -> Result<(), LedgerError> {
        let row = NewSkillUsageEvent {
            skill_name: event.skill_name,
            invoked_at: Utc::now().naive_utc(),
            role: event.role,
            model_id: event.model_id,
            tokens_in: event.tokens_in,
            tokens_out: event.tokens_out,
            tool_calls: event.tool_calls,
            success: event.success,
            task_id: event.task_id,
            conversation_id: event.conversation_id,
        };
        diesel::insert_into(skill_usage_events::table)
            .values(&row)
            .execute(self.conn)
            .map(|_| ())
            .map_err(|e| LedgerError::Diesel(e.to_string()))
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use diesel::Connection;
    use diesel_migrations::MigrationHarness;
    use persistence::schema::skill_usage_events::dsl;

    fn open_in_memory() -> SqliteConnection {
        let mut conn =
            SqliteConnection::establish(":memory:").expect("in-memory sqlite connection");
        conn.run_pending_migrations(persistence::MIGRATIONS)
            .expect("migrations must apply cleanly");
        conn
    }

    fn worker_event(skill: &str) -> UsageEvent {
        UsageEvent {
            skill_name: skill.to_string(),
            role: "Worker".to_string(),
            model_id: Some("dynamic/text_gen".to_string()),
            tokens_in: Some(120),
            tokens_out: Some(340),
            tool_calls: Some(2),
            success: true,
            task_id: Some("task-001".to_string()),
            conversation_id: Some("conv-abc".to_string()),
        }
    }

    #[test]
    fn append_inserts_one_row() {
        let mut conn = open_in_memory();
        Ledger::new(&mut conn)
            .append(worker_event("cloudflare-deploy"))
            .expect("append should succeed");

        let rows: Vec<String> = dsl::skill_usage_events
            .select(dsl::skill_name)
            .load(&mut conn)
            .expect("select skill_name");
        assert_eq!(rows, vec!["cloudflare-deploy"]);
    }

    #[test]
    fn multiple_appends_accumulate() {
        let mut conn = open_in_memory();
        for name in ["shell-tips", "cloudflare-deploy", "shell-tips"] {
            Ledger::new(&mut conn)
                .append(worker_event(name))
                .expect("append");
        }

        let count: i64 = dsl::skill_usage_events
            .count()
            .get_result(&mut conn)
            .expect("count");
        assert_eq!(count, 3, "three appends → three rows");
    }

    #[test]
    fn append_with_all_optional_fields_none() {
        let mut conn = open_in_memory();
        Ledger::new(&mut conn)
            .append(UsageEvent {
                skill_name: "bare-skill".to_string(),
                role: "Planner".to_string(),
                model_id: None,
                tokens_in: None,
                tokens_out: None,
                tool_calls: None,
                success: false,
                task_id: None,
                conversation_id: None,
            })
            .expect("append with no optional fields");

        let count: i64 = dsl::skill_usage_events
            .count()
            .get_result(&mut conn)
            .expect("count");
        assert_eq!(count, 1);
    }

    #[test]
    fn append_records_success_flag() {
        let mut conn = open_in_memory();

        let mut success_event = worker_event("some-skill");
        success_event.success = true;
        Ledger::new(&mut conn)
            .append(success_event)
            .expect("append success");

        let mut failure_event = worker_event("some-skill");
        failure_event.success = false;
        Ledger::new(&mut conn)
            .append(failure_event)
            .expect("append failure");

        let flags: Vec<bool> = dsl::skill_usage_events
            .select(dsl::success)
            .order(dsl::id.asc())
            .load(&mut conn)
            .expect("select success");
        assert_eq!(flags, vec![true, false]);
    }
}
