ALTER TABLE workflows ADD user_can_delete BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE workflows ADD is_pending BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notebooks ADD is_pending BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workflows ADD server_id BIGINTEGER;
ALTER TABLE notebooks ADD server_id BIGINTEGER;
