mod agent_settings;
mod ai_setup_slide;
mod bottom_nav;
mod customize_slide;
mod intention_slide;
mod intro_slide;
pub mod layout;
mod onboarding_slide;
mod progress_dots;
mod project_slide;
pub mod slide_content;
mod theme_picker_slide;
mod third_party_slide;
mod toggle_card;

pub use agent_settings::{AgentAutonomy, AgentDevelopmentSettings, OnboardingModelInfo};
pub use ai_setup_slide::AiSetupSlide;
pub use bottom_nav::onboarding_bottom_nav;
pub use customize_slide::CustomizeUISlide;
pub use intention_slide::IntentionSlide;
pub use intro_slide::{IntroSlide, IntroSlideEvent};
pub use onboarding_slide::OnboardingSlide;
pub use project_slide::{ProjectOnboardingSettings, ProjectSlide};
pub use theme_picker_slide::{ThemePickerSlide, ThemePickerSlideEvent};
pub use third_party_slide::ThirdPartySlide;
