use crate::ui::theme::Fill;
use warpui::elements::Icon as WarpUiIcon;

/// Default icon dimensions that apply to all icons used within the ui system.
pub const ICON_DIMENSIONS: f32 = 24.;

/// Icon enum to be used within the app in place of the warpui::elements::Icon directly. It
/// abstracts things like svg paths out and provides a utility method to convert into the actual Icon.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Icon {
    File,
    NodeJS,
    AtSign,
    Menu,
    Plus,
    Copy,
    Circle,
    CircleFilled,
    Queued,
    Triangle,
    CopyMenuItem,
    Duplicate,
    Notebook,
    Workflow,
    X,
    DotsVertical,
    DotsHorizontal,
    Trash,
    Terminal,
    TerminalInput,
    TextInput,
    ListCollapsed,
    ListOpen,
    AddTeammates,
    Folder,
    Find,
    FindAll,
    Globe,
    Globe4,
    Search,
    Lightbulb,
    LightbulbFilled,
    Gear,
    Settings,
    Keyboard,
    AiAssistant,
    Rename,
    Share,
    Share3,
    LogOut,
    Move,
    TextBlock,
    RunnableCommandBlock,
    BulletedListBlock,
    OrderedListBlock,
    HorizontalRuleBlock,
    EmbedBlock,
    TaskListBlock,
    HeaderBlock,
    Cloud,
    CloudFilled,
    CloudOffline,
    Compass,
    CreateTeam,
    WarpDrive,
    Warp,
    WarpLogoLight,
    ArrowLeft,
    ArrowBlockLeft,
    ArrowBlockUp,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    ArrowSplit,
    LinkExternal,
    CheckCircleBroken,
    Link,
    Refresh,
    RefreshCcw,
    RefreshCw04,
    AlertTriangle,
    Laptop,
    Tool,
    Tool2,
    CalendarDate,
    Gift,
    CalendarCheck,
    AlphaDescending,
    AlphaAscending,
    ReverseLeft,
    Pencil,
    Sort,
    Check,
    FilterFunnel,
    FilterFunnelFilled,
    FilterOff,
    Bug,
    Code1,
    Code2,
    Explain,
    Rocket,
    Rocket1,
    Regex,
    CaseSensitivity,
    PreserveCase,
    Import,
    Download,
    XCircle,
    SearchSmall,
    VimNormalMode,
    VimInsertMode,
    VimVisualMode,
    VimReplaceMode,
    Info,
    LinkHorizontal,
    Clock,
    Maximize,
    Minimize,
    Sharing,
    DistributeSpacingVertical,
    ChevronLeft,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    ChevronRightDouble,
    ChevronLeftDouble,
    ArrowDropDown,
    AlertCircle,
    Bold,
    Italic,
    Underline,
    InlineCode,
    Strikethrough,
    Stars,
    AgentMode,
    AmbientAgentMode,
    Github,
    Docker,
    Linear,
    Slack,
    Loading,
    Warning,
    HelpCircle,
    ThumbsUp,
    ThumbsDown,
    Repeat,
    Edit,
    EditLine,
    Eye,
    Slash,
    ClockRefresh,
    ClockRewind,
    ClockLoader,
    Paperclip,
    EnvVarCollection,
    CornerRight,
    DashedRectangle,
    CornersOfBox,
    Microphone,
    Stop,
    StopFilled,
    MinusCircle,
    Minus,
    Key,
    OnePassword,
    LastPass,
    SlashCircle,
    User,
    Users,
    CoinsStacked,
    Phone,
    Navigation,
    AutoUpdate,
    Bell,
    GitBranch,
    CheckSkinny,
    Lock,
    Save,
    CornerDownLeft,
    Powershell,
    GitBash,
    Ubuntu,
    Debian,
    Kali,
    Arch,
    Linux,
    Cancelled,
    BookOpen,
    LoadingDots0,
    LoadingDots1,
    LoadingDots2,
    LoadingDots3,
    LoadingBlinker0,
    LoadingBlinker1,
    LoadingBlinker2,
    PackageCheck,
    Liftoff0,
    Liftoff1,
    Liftoff2,
    Liftoff3,
    Liftoff4,
    LoadingAgents0,
    LoadingAgents1,
    LoadingAgents2,
    LoadingAgents3,
    LoadingAgents4,
    LoadingAgents5,
    LoadingAgents6,
    LoadingAgents7,
    Warping0,
    Warping1,
    Warping2,
    Warping3,
    Warping4,
    Warping5,
    Warping6,
    Warping7,
    Warping8,
    Warping9,
    Warping10,
    Warping11,
    FlipForward,
    PaintBrush,
    GamingPad,
    Neurology,
    Lightning,
    Orbit,
    PlusCircle,
    Dataflow,
    Play,
    MessageText,
    NewConversation,
    Image,
    FastForward,
    FastForwardFilled,
    ContextWindowTwentyPct,
    ContextWindowFourtyPct,
    ContextWindowSixtyPct,
    ContextWindowWarning,
    ContextWindowSummarized,
    ConversationContext0,
    ConversationContext10,
    ConversationContext20,
    ConversationContext30,
    ConversationContext40,
    ConversationContext50,
    ConversationContext60,
    ConversationContext70,
    ConversationContext80,
    ConversationContext90,
    ConversationContext100,
    LeftSidebarOpen,
    LeftSidebarClose,
    Diff,
    ExpandUp,
    ExpandDown,
    ExpandUpAndDown,
    Psychology,
    History,
    SlashCommands,
    MessagePlusSquare,
    Hash,
    FolderClosed,
    FileCopy,
    Credits,
    AddressedComment,
    ClockSnooze,
    Hand,
    ArrowCircleBrokenUp,
    FilterLines,
    ChatDashed,
    ClaudeLogo,
    GeminiLogo,
    OpenAILogo,
    AmpLogo,
    DroidLogo,
    OpenCodeLogo,
    CopilotLogo,
    PiLogo,
    AuggieLogo,
    CursorLogo,
    GooseLogo,
    NLD,
    Oz,
    OzCloud,
    Conversation,
    Prompt,
    Grid,
    Figma,
    FigmaColored,
    StripeLogo,
    CalloutTriangleBorderDown,
    CalloutTriangleFillDown,
    CalloutTriangleBorderUp,
    CalloutTriangleFillUp,
    CalloutTriangleBorderLeft,
    CalloutTriangleFillLeft,
    DragIndicator,
    Ellipse,
    Inbox,
    Menu01,
    LayoutAlt01,
    Dataflow02,
    Sliders,
    MessageCheckSquare,
    Phone01,
    GitCommit,
    UploadCloud,
    ClockPlus,
    SwitchHorizontal01,
    HeartHand,
    MessageChatSquare,
}

impl From<Icon> for &'static str {
    fn from(icon: Icon) -> &'static str {
        match icon {
            Icon::Menu => "bundled/svg/layout-left.svg",
            Icon::AtSign => "bundled/svg/at-sign.svg",
            Icon::Plus => "bundled/svg/plus.svg",
            Icon::Copy => "bundled/svg/copy.svg",
            Icon::Circle => "bundled/svg/circle.svg",
            Icon::CircleFilled => "bundled/svg/circle-filled.svg",
            Icon::Triangle => "bundled/svg/triangle.svg",
            Icon::Queued => "bundled/svg/queued.svg",
            Icon::CopyMenuItem => "bundled/svg/copy-05.svg",
            Icon::Duplicate => "bundled/svg/copy-07.svg",
            Icon::Notebook => "bundled/svg/notebook.svg",
            Icon::Workflow => "bundled/svg/workflow.svg",
            Icon::X => "bundled/svg/x-close.svg",
            Icon::ChevronLeft => "bundled/svg/chevron-left.svg",
            Icon::DotsVertical => "bundled/svg/dots-vertical.svg",
            Icon::DotsHorizontal => "bundled/svg/dots-horizontal.svg",
            Icon::Globe => "bundled/svg/globe-01.svg",
            Icon::Globe4 => "bundled/svg/globe-04.svg",
            Icon::Trash => "bundled/svg/trash-02.svg",
            Icon::Terminal => "bundled/svg/terminal.svg",
            Icon::TerminalInput => "bundled/svg/terminal-input.svg",
            Icon::TextInput => "bundled/svg/text-input.svg",
            Icon::ListCollapsed => "bundled/svg/chevron-right-2.svg",
            Icon::ListOpen => "bundled/svg/chevron-down-2.svg",
            Icon::Microphone => "bundled/svg/microphone.svg",
            Icon::Stop => "bundled/svg/stop.svg",
            Icon::StopFilled => "bundled/svg/stop-filled.svg",
            Icon::AddTeammates => "bundled/svg/user-plus-01.svg",
            Icon::Folder => "bundled/svg/folder.svg",
            Icon::Find => "bundled/svg/find.svg",
            Icon::FindAll => "bundled/svg/find-all.svg",
            Icon::Search => "bundled/svg/search.svg",
            Icon::Lightbulb => "bundled/svg/lightbulb.svg",
            Icon::LightbulbFilled => "bundled/svg/lightbulb-filled.svg",
            Icon::Gear => "bundled/svg/gear.svg",
            Icon::Settings => "bundled/svg/settings.svg",
            Icon::Keyboard => "bundled/svg/keyboard.svg",
            Icon::AiAssistant => "bundled/svg/ai-assistant.svg",
            Icon::Rename => "bundled/svg/pencil-line.svg",
            Icon::Share => "bundled/svg/share-01.svg",
            Icon::Share3 => "bundled/svg/share-03.svg",
            Icon::LogOut => "bundled/svg/log-out-01.svg",
            Icon::Move => "bundled/svg/move.svg",
            Icon::TextBlock => "bundled/svg/block-text.svg",
            Icon::RunnableCommandBlock => "bundled/svg/block-command.svg",
            Icon::HeaderBlock => "bundled/svg/block-header.svg",
            Icon::HorizontalRuleBlock => "bundled/svg/block-horizontal-rule.svg",
            Icon::EmbedBlock => "bundled/svg/block-embed.svg",
            Icon::BulletedListBlock => "bundled/svg/block-bulletedlist.svg",
            Icon::OrderedListBlock => "bundled/svg/block-ordered-list.svg",
            Icon::TaskListBlock => "bundled/svg/block-tasklist.svg",
            Icon::Cloud => "bundled/svg/cloud-01.svg",
            Icon::CloudFilled => "bundled/svg/cloud-filled.svg",
            Icon::CloudOffline => "bundled/svg/cloud-offline.svg",
            Icon::Compass => "bundled/svg/compass-3.svg",
            Icon::CreateTeam => "bundled/svg/create-team.svg",
            Icon::WarpDrive => "bundled/svg/warp.svg",
            Icon::Warp => "bundled/svg/warp-drive.svg",
            Icon::WarpLogoLight => "bundled/svg/warp-logo-light.svg",
            Icon::ArrowLeft => "bundled/svg/arrow-left.svg",
            Icon::ArrowBlockLeft => "bundled/svg/arrow-block-left.svg",
            Icon::ArrowBlockUp => "bundled/svg/arrow-block-up.svg",
            Icon::ArrowRight => "bundled/svg/arrow-right.svg",
            Icon::ArrowUp => "bundled/svg/arrow-narrow-up.svg",
            Icon::ArrowDown => "bundled/svg/arrow-narrow-down.svg",
            Icon::ArrowSplit => "bundled/svg/arrow-split.svg",
            Icon::SwitchHorizontal01 => "bundled/svg/switch-horizontal-01.svg",
            Icon::ArrowDropDown => "bundled/svg/arrow-drop-down.svg",
            Icon::CheckCircleBroken => "bundled/svg/check-circle-broken.svg",
            Icon::LinkExternal => "bundled/svg/link-external-02.svg",
            Icon::Link => "bundled/svg/link-03.svg",
            Icon::Refresh => "bundled/svg/refresh.svg",
            Icon::RefreshCcw => "bundled/svg/refresh-ccw-01.svg",
            Icon::RefreshCw04 => "bundled/svg/refresh-cw-04.svg",
            Icon::AlertTriangle => "bundled/svg/alert-triangle.svg",
            Icon::Laptop => "bundled/svg/laptop.svg",
            Icon::Tool => "bundled/svg/tool-01.svg",
            Icon::Tool2 => "bundled/svg/tool-02.svg",
            Icon::CalendarDate => "bundled/svg/calendar-date.svg",
            Icon::Gift => "bundled/svg/gift-01.svg",
            Icon::CalendarCheck => "bundled/svg/calendar-check-01.svg",
            Icon::AlphaDescending => "bundled/svg/Alpha descending.svg",
            Icon::AlphaAscending => "bundled/svg/Alpha ascending.svg",
            Icon::ReverseLeft => "bundled/svg/reverse-left.svg",
            Icon::Pencil => "bundled/svg/pencil-02.svg",
            Icon::Sort => "bundled/svg/sort.svg",
            Icon::Check => "bundled/svg/check.svg",
            Icon::FilterFunnel => "bundled/svg/filter-funnel.svg",
            Icon::FilterFunnelFilled => "bundled/svg/filter-funnel-filled.svg",
            Icon::FilterOff => "bundled/svg/filter-list-off.svg",
            Icon::Bug => "bundled/svg/bug.svg",
            Icon::Code1 => "bundled/svg/code-01.svg",
            Icon::Code2 => "bundled/svg/code-02.svg",
            Icon::Explain => "bundled/svg/explain.svg",
            Icon::Rocket => "bundled/svg/rocket.svg",
            Icon::Rocket1 => "bundled/svg/rocket-01.svg",
            Icon::Regex => "bundled/svg/regex.svg",
            Icon::CaseSensitivity => "bundled/svg/case-sensitive.svg",
            Icon::PreserveCase => "bundled/svg/preserve-case.svg",
            Icon::Import => "bundled/svg/import.svg",
            Icon::Download => "bundled/svg/download-02.svg",
            Icon::XCircle => "bundled/svg/x-circle.svg",
            Icon::SearchSmall => "bundled/svg/search-small.svg",
            Icon::VimNormalMode => "bundled/svg/vim-normal-mode.svg",
            Icon::VimInsertMode => "bundled/svg/vim-insert-mode.svg",
            Icon::VimVisualMode => "bundled/svg/vim-visual-mode.svg",
            Icon::VimReplaceMode => "bundled/svg/vim-replace-mode.svg",
            Icon::Info => "bundled/svg/info.svg",
            Icon::LinkHorizontal => "bundled/svg/link-horizontal.svg",
            Icon::Clock => "bundled/svg/clock.svg",
            Icon::Maximize => "bundled/svg/maximize-01.svg",
            Icon::Minimize => "bundled/svg/minimize-01.svg",
            Icon::Sharing => "bundled/svg/sharing.svg",
            Icon::DistributeSpacingVertical => "bundled/svg/distribute-spacing-vertical.svg",
            Icon::ChevronDown => "bundled/svg/chevron-down.svg",
            Icon::ChevronUp => "bundled/svg/chevron-up.svg",
            Icon::ChevronRightDouble => "bundled/svg/chevron-right-double.svg",
            Icon::ChevronLeftDouble => "bundled/svg/chevron-left-double.svg",
            Icon::AlertCircle => "bundled/svg/alert-circle.svg",
            Icon::Bold => "bundled/svg/edit-bold.svg",
            Icon::Italic => "bundled/svg/edit-italic.svg",
            Icon::Underline => "bundled/svg/edit-underline.svg",
            Icon::InlineCode => "bundled/svg/edit-code.svg",
            Icon::Strikethrough => "bundled/svg/edit-strikethrough.svg",
            Icon::Stars => "bundled/svg/stars-01.svg",
            Icon::AgentMode => "bundled/svg/agentmode.svg",
            Icon::AmbientAgentMode => "bundled/svg/ambient-agent-mode.svg",
            Icon::Github => "bundled/svg/github.svg",
            Icon::Docker => "bundled/svg/docker.svg",
            Icon::Linear => "bundled/svg/linear.svg",
            Icon::Slack => "bundled/svg/slack-logo.svg",
            Icon::ChevronRight => "bundled/svg/chevron-right.svg",
            Icon::Loading => "bundled/svg/loading-02.svg",
            Icon::Warning => "bundled/svg/warning.svg",
            Icon::HelpCircle => "bundled/svg/help-circle.svg",
            Icon::ThumbsUp => "bundled/svg/thumbs-up.svg",
            Icon::ThumbsDown => "bundled/svg/thumbs-down.svg",
            Icon::Repeat => "bundled/svg/repeat-01.svg",
            Icon::Edit => "bundled/svg/edit-01.svg",
            Icon::EditLine => "bundled/svg/edit-03.svg",
            Icon::Eye => "bundled/svg/eye.svg",
            Icon::Slash => "bundled/svg/slash.svg",
            Icon::ClockRefresh => "bundled/svg/clock-refresh.svg",
            Icon::ClockRewind => "bundled/svg/clock-rewind.svg",
            Icon::ClockLoader => "bundled/svg/clock-loader.svg",
            Icon::Paperclip => "bundled/svg/paperclip.svg",
            Icon::EnvVarCollection => "bundled/svg/env-var-collection.svg",
            Icon::CornerRight => "bundled/svg/corner-right.svg",
            Icon::DashedRectangle => "bundled/svg/dashed-rectangle.svg",
            Icon::CornersOfBox => "bundled/svg/corners-of-box.svg",
            Icon::MinusCircle => "bundled/svg/minus-circle.svg",
            Icon::Minus => "bundled/svg/minus.svg",
            Icon::Key => "bundled/svg/key.svg",
            Icon::OnePassword => "bundled/svg/onepassword.svg",
            Icon::LastPass => "bundled/svg/lastpass.svg",
            Icon::SlashCircle => "bundled/svg/slash-circle-01.svg",
            Icon::User => "bundled/svg/user-02.svg",
            Icon::Users => "bundled/svg/users-02.svg",
            Icon::CoinsStacked => "bundled/svg/coins-stacked-02.svg",
            Icon::Phone => "bundled/svg/phone.svg",
            Icon::Navigation => "bundled/svg/navigation.svg",
            Icon::AutoUpdate => "bundled/svg/autoupdate.svg",
            Icon::Bell => "bundled/svg/bell.svg",
            Icon::GitBranch => "bundled/svg/git-branch-02.svg",
            Icon::CheckSkinny => "bundled/svg/check-skinny.svg",
            Icon::Lock => "bundled/svg/lock-unlocked-01.svg",
            Icon::Save => "bundled/svg/download-01.svg",
            Icon::CornerDownLeft => "bundled/svg/corner-down-left.svg",
            Icon::Powershell => "bundled/svg/powershell.svg",
            Icon::GitBash => "bundled/svg/git-bash.svg",
            Icon::Ubuntu => "bundled/svg/ubuntu.svg",
            Icon::Debian => "bundled/svg/debian.svg",
            Icon::Kali => "bundled/svg/kali.svg",
            Icon::Arch => "bundled/svg/arch.svg",
            Icon::Linux => "bundled/svg/linux.svg",
            Icon::Cancelled => "bundled/svg/cancelled.svg",
            Icon::BookOpen => "bundled/svg/book-open.svg",
            Icon::LoadingDots0 => "bundled/svg/dots-0.svg",
            Icon::LoadingDots1 => "bundled/svg/dots-1.svg",
            Icon::LoadingDots2 => "bundled/svg/dots-2.svg",
            Icon::LoadingDots3 => "bundled/svg/dots-3.svg",
            Icon::LoadingBlinker0 => "bundled/svg/blinker-0.svg",
            Icon::LoadingBlinker1 => "bundled/svg/blinker-1.svg",
            Icon::LoadingBlinker2 => "bundled/svg/blinker-2.svg",
            Icon::PackageCheck => "bundled/svg/package-check.svg",
            Icon::Liftoff0 => "bundled/svg/liftoff-0.svg",
            Icon::Liftoff1 => "bundled/svg/liftoff-1.svg",
            Icon::Liftoff2 => "bundled/svg/liftoff-2.svg",
            Icon::Liftoff3 => "bundled/svg/liftoff-3.svg",
            Icon::Liftoff4 => "bundled/svg/liftoff-4.svg",
            Icon::LoadingAgents0 => "bundled/svg/loading-agents-01.svg",
            Icon::LoadingAgents1 => "bundled/svg/loading-agents-02.svg",
            Icon::LoadingAgents2 => "bundled/svg/loading-agents-03.svg",
            Icon::LoadingAgents3 => "bundled/svg/loading-agents-04.svg",
            Icon::LoadingAgents4 => "bundled/svg/loading-agents-05.svg",
            Icon::LoadingAgents5 => "bundled/svg/loading-agents-06.svg",
            Icon::LoadingAgents6 => "bundled/svg/loading-agents-07.svg",
            Icon::LoadingAgents7 => "bundled/svg/loading-agents-08.svg",
            Icon::Warping0 => "bundled/svg/warp-loading-0.svg",
            Icon::Warping1 => "bundled/svg/warp-loading-1.svg",
            Icon::Warping2 => "bundled/svg/warp-loading-2.svg",
            Icon::Warping3 => "bundled/svg/warp-loading-3.svg",
            Icon::Warping4 => "bundled/svg/warp-loading-4.svg",
            Icon::Warping5 => "bundled/svg/warp-loading-5.svg",
            Icon::Warping6 => "bundled/svg/warp-loading-6.svg",
            Icon::Warping7 => "bundled/svg/warp-loading-7.svg",
            Icon::Warping8 => "bundled/svg/warp-loading-8.svg",
            Icon::Warping9 => "bundled/svg/warp-loading-9.svg",
            Icon::Warping10 => "bundled/svg/warp-loading-10.svg",
            Icon::Warping11 => "bundled/svg/warp-loading-11.svg",
            Icon::FlipForward => "bundled/svg/flip-forward.svg",
            Icon::PaintBrush => "bundled/svg/brush-01.svg",
            Icon::GamingPad => "bundled/svg/gaming-pad-01.svg",
            Icon::Neurology => "bundled/svg/neurology.svg",
            Icon::Lightning => "bundled/svg/lightning-02.svg",
            Icon::Orbit => "bundled/svg/orbit.svg",
            Icon::PlusCircle => "bundled/svg/plus-circle.svg",
            Icon::Dataflow => "bundled/svg/dataflow.svg",
            Icon::Play => "bundled/svg/play-white.svg",
            Icon::MessageText => "bundled/svg/message-text-square-02.svg",
            Icon::NewConversation => "bundled/svg/new-conversation.svg",
            Icon::Image => "bundled/svg/image-01.svg",
            Icon::File => "bundled/svg/file.svg",
            Icon::NodeJS => "bundled/svg/nodejs-logo.svg",
            Icon::FastForward => "bundled/svg/fast-forward.svg",
            Icon::FastForwardFilled => "bundled/svg/fast-forward-filled.svg",
            Icon::ContextWindowTwentyPct => "bundled/svg/context-window-20-pct.svg",
            Icon::ContextWindowFourtyPct => "bundled/svg/context-window-40-pct.svg",
            Icon::ContextWindowSixtyPct => "bundled/svg/context-window-60-pct.svg",
            Icon::ContextWindowWarning => "bundled/svg/context-window-warning.svg",
            Icon::ContextWindowSummarized => "bundled/svg/context-window-summarized.svg",
            Icon::ConversationContext0 => "bundled/svg/conversation-context-0.svg",
            Icon::ConversationContext10 => "bundled/svg/conversation-context-10.svg",
            Icon::ConversationContext20 => "bundled/svg/conversation-context-20.svg",
            Icon::ConversationContext30 => "bundled/svg/conversation-context-30.svg",
            Icon::ConversationContext40 => "bundled/svg/conversation-context-40.svg",
            Icon::ConversationContext50 => "bundled/svg/conversation-context-50.svg",
            Icon::ConversationContext60 => "bundled/svg/conversation-context-60.svg",
            Icon::ConversationContext70 => "bundled/svg/conversation-context-70.svg",
            Icon::ConversationContext80 => "bundled/svg/conversation-context-80.svg",
            Icon::ConversationContext90 => "bundled/svg/conversation-context-90.svg",
            Icon::ConversationContext100 => "bundled/svg/conversation-context-100.svg",
            Icon::LeftSidebarOpen => "bundled/svg/left-panel-open.svg",
            Icon::LeftSidebarClose => "bundled/svg/left-panel-close.svg",
            Icon::Diff => "bundled/svg/diff.svg",
            Icon::ExpandUp => "bundled/svg/expand-up.svg",
            Icon::ExpandDown => "bundled/svg/expand-down.svg",
            Icon::ExpandUpAndDown => "bundled/svg/expand-up-and-down.svg",
            Icon::Psychology => "bundled/svg/psychology.svg",
            Icon::History => "bundled/svg/history.svg",
            Icon::SlashCommands => "bundled/svg/slash-square.svg",
            Icon::MessagePlusSquare => "bundled/svg/message-plus-square.svg",
            Icon::Hash => "bundled/svg/hash-02.svg",
            Icon::FolderClosed => "bundled/svg/folder-closed.svg",
            Icon::FileCopy => "bundled/svg/file_copy.svg",
            Icon::Credits => "bundled/svg/credits.svg",
            Icon::AddressedComment => "bundled/svg/addressed-comment.svg",
            Icon::ClockSnooze => "bundled/svg/clock-snooze.svg",
            Icon::Hand => "bundled/svg/hand.svg",
            Icon::ArrowCircleBrokenUp => "bundled/svg/arrow-circle-broken-up.svg",
            Icon::FilterLines => "bundled/svg/filter-lines.svg",
            Icon::ChatDashed => "bundled/svg/chat-dashed.svg",
            Icon::ClaudeLogo => "bundled/svg/claude.svg",
            Icon::GeminiLogo => "bundled/svg/gemini_cli.svg",
            Icon::OpenAILogo => "bundled/svg/openai.svg",
            Icon::AmpLogo => "bundled/svg/amp.svg",
            Icon::DroidLogo => "bundled/svg/droid.svg",
            Icon::OpenCodeLogo => "bundled/svg/opencode.svg",
            Icon::CopilotLogo => "bundled/svg/copilot.svg",
            Icon::PiLogo => "bundled/svg/pi.svg",
            Icon::AuggieLogo => "bundled/svg/auggie.svg",
            Icon::CursorLogo => "bundled/svg/cursor.svg",
            Icon::GooseLogo => "bundled/svg/goose.svg",
            Icon::NLD => "bundled/svg/nld.svg",
            Icon::Oz => "bundled/svg/oz.svg",
            Icon::OzCloud => "bundled/svg/oz-cloud.svg",
            Icon::Conversation => "bundled/svg/conversation.svg",
            Icon::Prompt => "bundled/svg/prompt.svg",
            Icon::Grid => "bundled/svg/grid.svg",
            Icon::Figma => "bundled/svg/figma.svg",
            Icon::FigmaColored => "bundled/svg/figma-colored.svg",
            Icon::StripeLogo => "bundled/svg/stripe.svg",
            Icon::CalloutTriangleBorderDown => "bundled/svg/callout-triangle-border-down.svg",
            Icon::CalloutTriangleFillDown => "bundled/svg/callout-triangle-fill-down.svg",
            Icon::CalloutTriangleBorderUp => "bundled/svg/callout-triangle-border-up.svg",
            Icon::CalloutTriangleFillUp => "bundled/svg/callout-triangle-fill-up.svg",
            Icon::CalloutTriangleBorderLeft => "bundled/svg/callout-triangle-border-left.svg",
            Icon::CalloutTriangleFillLeft => "bundled/svg/callout-triangle-fill-left.svg",
            Icon::DragIndicator => "bundled/svg/drag_indicator.svg",
            Icon::Ellipse => "bundled/svg/ellipse.svg",
            Icon::Inbox => "bundled/svg/inbox-01.svg",
            Icon::Menu01 => "bundled/svg/menu-01.svg",
            Icon::LayoutAlt01 => "bundled/svg/layout-alt-01.svg",
            Icon::Dataflow02 => "bundled/svg/dataflow-02.svg",
            Icon::Sliders => "bundled/svg/sliders-04.svg",
            Icon::MessageCheckSquare => "bundled/svg/message-check-square.svg",
            Icon::Phone01 => "bundled/svg/phone-01.svg",
            Icon::GitCommit => "bundled/svg/git-commit.svg",
            Icon::UploadCloud => "bundled/svg/upload-cloud-01.svg",
            Icon::ClockPlus => "bundled/svg/clock-plus.svg",
            Icon::HeartHand => "bundled/svg/heart-hand.svg",
            Icon::MessageChatSquare => "bundled/svg/message-chat-square.svg",
        }
    }
}

impl Icon {
    pub fn to_warpui_icon(self, color: Fill) -> WarpUiIcon {
        WarpUiIcon::new(self.into(), color.into_solid())
    }

    pub fn icon_for_key(key: &str) -> Option<WarpUiIcon> {
        match key {
            "⏎" => Some(Self::CornerDownLeft.to_warpui_icon(Fill::black())),
            _ => None,
        }
    }
}
