use super::super::proto;
use crate::code_review::diff_size_limits::DiffSize;
use crate::code_review::diff_state::{
    DiffMetadata, DiffMetadataAgainstBase, FileDiff, FileStatusInfo, GitFileStatus,
};
use std::path::PathBuf;
use std::sync::Arc;
use warp_util::standardized_path::StandardizedPath;

// ── FileStatusInfo path validation (TryFrom) ────────────────────

#[test]
fn file_status_info_valid_absolute_path() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/src/main.rs".into(),
        status: Some(proto::GitFileStatus {
            status: Some(proto::git_file_status::Status::NewFile(
                proto::GitFileStatusNew {},
            )),
        }),
    };

    let info = FileStatusInfo::try_from(&proto_info).unwrap();
    assert_eq!(
        info.path,
        StandardizedPath::try_new("/repo/src/main.rs").unwrap()
    );
    assert_eq!(info.status, GitFileStatus::New);
}

#[test]
fn file_status_info_missing_status_is_error() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/file.rs".into(),
        status: None,
    };

    assert!(FileStatusInfo::try_from(&proto_info).is_err());
}

#[test]
fn file_status_info_missing_status_variant_is_error() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/file.rs".into(),
        status: Some(proto::GitFileStatus { status: None }),
    };

    assert!(FileStatusInfo::try_from(&proto_info).is_err());
}

#[test]
fn file_status_info_validates_renamed_old_path() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/new_name.rs".into(),
        status: Some(proto::GitFileStatus {
            status: Some(proto::git_file_status::Status::Renamed(
                proto::GitFileStatusRenamed {
                    old_path: "relative/old.rs".into(),
                },
            )),
        }),
    };

    // old_path is relative — should fail validation.
    assert!(FileStatusInfo::try_from(&proto_info).is_err());
}

#[test]
fn diff_metadata_requires_against_head() {
    let metadata = proto::DiffMetadata {
        main_branch_name: "main".into(),
        current_branch_name: "feature".into(),
        against_head: None,
        against_base_branch: None,
        has_head_commit: true,
        unpushed_commits: vec![],
        upstream_ref: None,
        pr_info: None,
    };

    assert!(DiffMetadata::try_from(&metadata).is_err());
}

#[test]
fn diff_metadata_against_base_requires_stats() {
    let against_base = proto::DiffMetadataAgainstBase {
        aggregate_stats: None,
    };

    assert!(DiffMetadataAgainstBase::try_from(&against_base).is_err());
}

#[test]
fn file_diff_to_proto_standardizes_relative_path_against_repo() {
    let file_diff = FileDiff {
        file_path: PathBuf::from("src/main.rs"),
        status: GitFileStatus::Modified,
        hunks: Arc::new(vec![]),
        is_binary: false,
        is_autogenerated: false,
        max_line_number: 0,
        has_hidden_bidi_chars: false,
        size: DiffSize::Normal,
    };

    let proto_diff = super::file_diff_to_proto("/repo", &file_diff, None);

    assert_eq!(proto_diff.file_path, "/repo/src/main.rs");
}
